# 1. Load modules and data

In [1]:
# Load modules
import pandas as pd
import os
import numpy as np  
import matplotlib.pyplot as plt
import seaborn as sns

# Set display options
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 1000)

In [2]:
# Load two final merged dataframes
# Path
path = r'/Users/tyrasmussen/Desktop/FVTC/Spring 2026/Data Analytics Capstone/MM/MM Data/Merged'

In [3]:
# Load KenPom and Reference Data
full_kenpom_df = pd.read_csv(os.path.join(path, 'FINAL _ Merged KenPom and Reference Data.csv'))

In [4]:
# Load Team Master Data
team_master = pd.read_csv(os.path.join(path, 'FINAL_Team_Master_2008_2025.csv'))

/var/folders/l9/n_0jq3zj66l9v7k98dd7cpqc0000gn/T/ipykernel_59627/1873934295.py:2: DtypeWarning: Columns (2,27,41,125,209,293,376,379,380,381,382,383,385,398,403,500,522,523,524,525,526,527,528,530,544,547,548,582,597,612,627,671,674,675,676,677,679,682,683,684,685,687,690,691,700,708,713) have mixed types. Specify dtype option on import or set low_memory=False.
  team_master = pd.read_csv(os.path.join(path, 'FINAL_Team_Master_2008_2025.csv'))

In [5]:
full_kenpom_df.head()

,Season,TeamName,eFGPct_off,RankeFGPct_off,TOPct_off,RankTOPct_off,ORPct_off,RankORPct_off,FTRate_off,RankFTRate_off,eFGPct_def,RankeFGPct_def,TOPct_def,RankTOPct_def,ORPct_def,RankORPct_def,FTRate_def,RankFTRate_def,Conference_extra,Adjusted Temo_extra,Adjusted Tempo Rank_extra,Raw Tempo_extra,Raw Tempo Rank_extra,Adjusted Offensive Efficiency_extra,Adjusted Offensive Efficiency Rank_extra,Raw Offensive Efficiency_extra,Raw Offensive Efficiency Rank_extra,Adjusted Defensive Efficiency_extra,Adjusted Defensive Efficiency Rank_extra,Raw Defensive Efficiency_extra,Raw Defensive Efficiency Rank_extra,Avg Possession Length (Offense)_extra,Avg Possession Length (Offense) Rank_extra,Avg Possession Length (Defense)_extra,Avg Possession Length (Defense) Rank_extra,AvgHeight_extra,RankAvgHeight_extra,CenterHeight_extra,RankCenterHeight_extra,PFHeight_extra,RankPFHeight_extra,SFHeight_extra,RankSFHeight_extra,SGHeight_extra,RankSGHeight_extra,PGHeight_extra,RankPGHeight_extra,EffectiveHeight_extra,RankEffectiveHeight_extra,Experience_extra,RankExperience_extra,Bench_extra,BenchRank_extra,CenterPts_extra,RankCenterPts_extra,PFPts_extra,RankPFPts_extra,SFPts_extra,RankSFPts_extra,SGPts_extra,RankSGPts_extra,PGPts_extra,RankPGPts_extra,CenterOR_extra,RankCenterOR_extra,PFOR_extra,RankPFOR_extra,SFOR_extra,RankSFOR_extra,SGOR_extra,RankSGOR_extra,PGOR_extra,RankPGOR_extra,CenterDR_extra,RankCenterDR_extra,PFDR_extra,RankPFDR_extra,SFDR_extra,RankSFDR_extra,SGDR_extra,RankSGDR_extra,PGDR_extra,RankPGDR_extra,FG2Pct_extra,RankFG2Pct_extra,FG3Pct_extra,RankFG3Pct_extra,FTPct_extra,RankFTPct_extra,BlockPct_extra,RankBlockPct_extra,OppFG2Pct_extra,RankOppFG2Pct_extra,OppFG3Pct_extra,RankOppFG3Pct_extra,OppFTPct_extra,RankOppFTPct_extra,OppBlockPct_extra,RankOppBlockPct_extra,FG3Rate_extra,RankFG3Rate_extra,OppFG3Rate_extra,RankOppFG3Rate_extra,ARate_extra,RankARate_extra,OppARate_extra,RankOppARate_extra,StlRate_extra,RankStlRate_extra,OppStlRate_extra,RankOppStlRate_extra,DFP_extra,NSTRate_extra,RankNSTRate_extra,OppNSTRate_extra,RankOppNSTRate_extra,OffFT_extra,RankOffFT_extra,Off2PtFG_extra,RankOff2PtFG_extra,Off3PtFG_extra,RankOff3PtFG_extra,DefFT_extra,RankDefFT_extra,Def2PtFG_extra,RankDef2PtFG_extra,Def3PtFG_extra,RankDef3PtFG_extra,Tempo_extra_x,RankTempo_extra_x,AdjTempo_extra_x,RankAdjTempo_extra_x,OE_extra_x,RankOE_extra_x,AdjOE_extra_x,RankAdjOE_extra_x,DE_extra_x,RankDE_extra_x,AdjDE_extra_x,RankAdjDE_extra_x,AdjEM_extra_x,RankAdjEM_extra_x,Seed_extra,Tempo_extra_y,RankTempo_extra_y,AdjTempo_extra_y,RankAdjTempo_extra_y,OE_extra_y,RankOE_extra_y,AdjOE_extra_y,RankAdjOE_extra_y,DE_extra_y,RankDE_extra_y,AdjDE_extra_y,RankAdjDE_extra_y,AdjEM_extra_y,RankAdjEM_extra_y,Seed_ref,Region_ref,Post-Season Tournament_ref,Post-Season Tournament Sorting Index_ref,Vulnerable Top 2 Seed?_ref,Tournament Winner?_ref,Tournament Championship?_ref,Final Four?_ref,Top 12 in AP Top 25 During Week 6?_ref,Conference,Mapped Conference Name,Mapped ESPN Team Name
0,2025,Abilene Christian,46.689148,332.0,20.740433,350.0,30.069238,178.0,37.155120,57.0,51.411290,211.0,24.010102,1.0,31.450720,263.0,51.276882,364.0,WAC,69.6,65.0,70.1,73.0,97.7,330.0,95.7,346.0,102.3,92.0,100.8,54.0,16.8,79.0,17.5,145.0,77.31,163.0,-0.37,209.0,-0.84,281.0,-0.23,226.0,0.68,95.0,1.31,67.0,-0.60,259.0,1.34123,253.0,34.05,103.0,23.57,63.0,23.58,52.0,23.82,59.0,12.66,362.0,16.37,298.0,30.57,272.0,29.91,104.0,22.05,77.0,7.76,284.0,9.71,129.0,19.37,343.0,26.10,87.0,22.05,86.0,16.78,161.0,15.70,122.0,47.826087,295.0,28.883495,355.0,71.947195,195.0,8.366534,226.0,52.589641,251.0,32.644628,107.0,69.200524,31.0,11.156686,317.0,25.260576,362.0,32.526882,15.0,51.566952,178.0,51.603499,178.0,0.142011,3.0,0.111754,317.0,NaN,9.565000,348.0,9.809005,12.0,22.256253,31.0,59.520163,3.0,18.223583,362.0,25.655977,1.0,51.311953,110.0,23.032070,360.0,70.0679,72.0,69.3532,67.0,95.6706,346.0,97.6324,328.0,100.773,60.0,102.0970,86.0,-4.46503,219.0,NaN,70.0679,73.0,69.6271,65.0,95.6706,346.0,97.6737,330.0,100.773,54.0,102.3350,92.0,-4.66102,221.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Slnd,Southland Conference (SLC),Abilene Christian
1,2025,Abilene Christian,46.689148,332.0,20.740433,350.0,30.069238,178.0,37.155120,57.0,51.411290,211.0,24.010102,1.0,31.450720,263.0,51.276882,364.0,WAC,69.6,65.0,70.1,73.0,97.7,330.0,95.7,346.0,102.3,92.0,100.8,54.0,16.8,79.0,17.5,145.0,77.31,163.0,-0.37,209.0,-0.84,281.0,-0.23,226.0,0.68,95.0,1.31,67.0,-0.60,259.0,1.34123,253.0,34.05,103.0,23.57,63.0,23.58,52.0,23.82,59.0,12.66,362.0,16.37,298.0,30.57,272.0,29.91,104.0,22.05,77.0,7.76,284.0,9.71,129.0,19.37,343.0,26.10,87.0,22.05,86.0,16.78,161.0,15.70,122.0,47.826087,295.0,28.883495,355.0,71.947195,195.0,8.366534,226.0,52.589641,251.0,32.644628,107.0,69.200524,31.0,11.156686,317.0,25.260576,362.0,32.526882,15.0,51.566952,178.0,51.603499,178.0,0.142011,3.0,0.111754,317.0,NaN,9.565000,348.0,9.809005,12.0,22.256253,31.0,59.520163,3.0,18.223583,362.0,25.655977,1.0,51.311953,110.0,23.032070,360.0,70.0679,72.0,69.3532,67.0,95.6706,346.0,97.6324,328.0,100.773,60.0,102.0970,86.0,-4.46503,219.0,NaN,70.0679,73.0,69.6271,65.0,95.6706,346.0,97.6737,330.0,100.773,54.0,102.3350,92.0,-4.66102,221.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WAC,Western Athletic Conference (WAC),Abilene Christian
2,2025,Air Force,50.092822,220.0,20.721288,348.0,22.736031,343.0,35.396040,108.0,54.635950,334.0,15.684864,279.0,29.064039,142.0,35.437998,242.0,MWC,64.6,325.0,64.7,335.0,98.9,312.0,95.3,347.0,111.7,272.0,113.1,335.0,19.8,357.0,17.0,46.0,78.18,46.0,1.08,75.0,-0.23,212.0,0.01,178.0,1.13,61.0,2.88,6.0,0.43,120.0,1.78985,166.0,28.89,255.0,26.40,18.0,22.02,92.0,18.77,217.0,19.57,225.0,13.19,357.0,34.11,218.0,18.56,315.0,15.99,214.0,14.11,94.0,17.19,16.0,17.93,355.0,15.96,353.0,21.71,95.0,25.38,4.0,18.97,38.0,50.540216,201.0,33.077905,211.0,63.461538,359.0,8.028546,251.0,54.772525,320.0,36.263736,323.0,69.983949,63.0,12.364946,347.0,48.452970,14.0,36.234357,92.0,62.941176,6.0,48.639053,97.0,0.086818,265.0,0.104566,257.0,NaN,10.264712,357.0,7.003028,242.0,18.314834,221.0,42.482341,349.0,39.202825,18.0,18.498091,216.0,52.100127,82.0,29.401782,271.0,64.6651,334.0,64.3683,324.0,95.3082,347.0,98.9012,312.0,113.105,335.0,111.4670,272.0,-12.56550,310.0,NaN,64.6651,335.0,64.6373,325.0,95.3082,347.0,98.9098,312.0,113.105,335.0,111.6740,272.0,-12.76410,310.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MWC,Mountain West Conference (MW),Air Force
3,2025,Akron,54.940898,34.0,16.354727,131.0,32.179054,108.0,26.950355,332.0,50.073783,134.0,17.270259,167.0,29.474548,161.0,33.054599,184.0,MAC,71.7,15.0,72.5,10.0,113.6,71.0,114.9,29.0,107.1,182.0,105.1,154.0,15.8,21.0,17.1,62.0,75.06,361.0,-1.94,351.0,-3.52,364.0,-2.16,359.0,-1.36,327.0,-1.75,324.0,-2.73,364.0,1.39962,245.0,38.91,30.0,19.00,192.0,17.71,257.0,21.16,130.0,17.74,287.0,24.35,69.0,48.76,16.0,18.17,321.0,14.88,235.0,11.53,159.0,6.57,255.0,33.22,18.0,19.19,299.0,20.43,135.0,15.44,214.0,11.65,312.0,55.220017,41.0,36.401674,50.0,75.087719,76.0,9.754163,144.0,50.991277,180.0,32.383420,92.0,72.321429,197.0,7.506471,32.0,45.200946,54.0,37.973438,146.0,57.894737,50.0,45.128779,29.0,0.102789,126.0,0.097795,196.0,NaN,6.575183,77.0,6.991334,244.0,15.552326,338.0,46.511628,276.0,37.936047,43.0,19.270420,157.0,50.991277,119.0,29.738303,253.0,72.4588,15.0,71.3708,16.0,115.7540,22.0,113.6890,66.0,104.558,145.0,107.1090,183.0,6.57907,99.0,13.0,72.5396,10.0,71.6561,15.0,114.8680,29.0,113.5550,71.0,105.141,154.0,107.0810,182.0,6.47358,100.0,13.0,East,March Madness,1.0,NaN,NaN,NaN,NaN,NaN,MAC,Mid-American Conference (MAC),Akron
4,2025,Alabama,56.600590,10.0,16.559930,142.0,33.725202,64.0,39.308309,30.0,47.820055,49.0,13.488046,351.0,29.426752,159.0,33.174792,187.0,SEC,75.3,1.0,76.1,1.0,126.8,4.0,118.4,9.0,96.5,28.0,106.2,175.0,14.9,4.0,16.7,15.0,78.07,61.0,1.61,33.0,3.10,2.0,0.21,149.0,-0.47,254.0,-0.12,206.0,2.35,5.0,2.98697,9.0,38.57,33.0,15.78,301.0,19.15,199.0,18.97,205.0,20.78,167.0,25.32,50.0,29.10,301.0,29.93,102.0,26.62,29.0,9.42,230.0,4.92,328.0,26.91,148.0,29.47,25.0,20.19,149.0,12.26,329.0,11.16,327.0,59.747435,4.0,35.326087,93.0,71.995708,192.0,10.121212,127.0,49.030303,98.0,30.355097,19.0,70.967742,118.0,12.075770,343.0,46.562632,35.0,34.601665,44.0,55.448997,91.0,44.692737,24.0,0.080505,317.0,0.101690,233.0,NaN,6.390933,56.0,5.437589,362.0,20.000000,121.0,45.126677,313.0,34.873323,86.0,19.753908,135.0,53.807782,36.0,26.438311,340.0,76.2512,1.0,74.8553,1.0,118.7250,9.0,126.5110,4.0,106.121,176.0,96.5798,32.0,29.93170,6.0,2.0,76.0703,1.0,75.2702,1.0,118.4340,9.0,126.8140,4.0,106.226,175.0,96.4694,28.0,30.34500,6.0,2.0,East,March Madness,1.0,No,NaN,NaN,NaN,Yes,SEC,Southeastern Conference (SEC),Alabama

In [6]:
team_master.head()

,YEAR,TEAM NO,TEAM,SEED,ROUND,O RATE,D RATE,RELATIVE RATING,OPPONENT ADJUST,PACE ADJUST,O RATE RANK,D RATE RANK,TRUE TEMPO,TRUE TEMPO RANK,HOME RANK,KILL SHOTS PER GAME,KILL SHOTS CONCEDED PER GAME,TOTAL KILL SHOTS,TOTAL KILL SHOTS CONCEDED,RELATIVE RATING RANK,OPPONENT ADJUST RANK,PACE ADJUST RANK,KILL SHOTS PER GAME RANK,KILL SHOTS CONCEDED PER GAME RANK,TOTAL KILL SHOTS RANK,TOTAL KILL SHOTS CONCEDED RANK,YEAR_part2_x,TEAM_part2_x,SEED_part2_x,ROUND_part2_x,POWER RATING_part2,POWER RATING RANK_part2,YEAR_part2_y,TEAM_part2_y,SEED_part2_y,ROUND_part2_y,AP VOTES_part2_x,AP RANK_part2_x,RANK?_part2_x,YEAR_part2_x.1,TEAM ID_part2_x,TEAM_part2_x.1,SEED_part2_x.1,ROUND_part2_x.1,BADJ EM_part2_x,BADJ O_part2_x,BADJ D_part2_x,BARTHAG_part2_x,GAMES_part2_x,W_part2_x,L_part2_x,WIN%_part2_x,EFG%_part2_x,EFG%D_part2_x,FTR_part2_x,FTRD_part2_x,TOV%_part2_x,TOV%D_part2_x,OREB%_part2_x,DREB%_part2_x,OP OREB%_part2_x,OP DREB%_part2_x,RAW T_part2_x,2PT%_part2_x,2PT%D_part2_x,3PT%_part2_x,3PT%D_part2_x,BLK%_part2_x,BLKED%_part2_x,AST%_part2_x,OP AST%_part2_x,2PTR_part2_x,3PTR_part2_x,2PTRD_part2_x,3PTRD_part2_x,BADJ T_part2_x,AVG HGT_part2_x,EFF HGT_part2_x,EXP_part2_x,TALENT_part2_x,FT%_part2_x,OP FT%_part2_x,PPPO_part2_x,PPPD_part2_x,ELITE SOS_part2_x,WAB_part2_x,BADJ EM RANK_part2_x,BADJ O RANK_part2_x,BADJ D RANK_part2_x,BARTHAG RANK_part2_x,EFG% RANK_part2_x,EFGD% RANK_part2_x,FTR RANK_part2_x,FTRD RANK_part2_x,TOV% RANK_part2_x,TOV%D RANK_part2_x,OREB% RANK_part2_x,DREB% RANK_part2_x,OP OREB% RANK_part2_x,OP DREB% RANK_part2_x,RAW T RANK_part2_x,2PT% RANK_part2_x,2PT%D RANK_part2_x,3PT% RANK_part2_x,3PT%D RANK_part2_x,BLK% RANK_part2_x,BLKED% RANK_part2_x,AST% RANK_part2_x,OP AST% RANK_part2_x,2PTR RANK_part2_x,3PTR RANK_part2_x,2PTRD RANK_part2_x,3PTRD RANK_part2_x,BADJT RANK_part2_x,AVG HGT RANK_part2_x,EFF HGT RANK_part2_x,EXP RANK_part2_x,TALENT RANK_part2_x,FT% RANK_part2_x,OP FT% RANK_part2_x,PPPO RANK_part2_x,PPPD RANK_part2_x,ELITE SOS RANK_part2_x,YEAR_part2_y.1,TEAM ID_part2_y,TEAM_part2_y.1,SEED_part2_y.1,ROUND_part2_y.1,BADJ EM_part2_y,BADJ O_part2_y,BADJ D_part2_y,BARTHAG_part2_y,GAMES_part2_y,W_part2_y,L_part2_y,WIN%_part2_y,EFG%_part2_y,EFG%D_part2_y,FTR_part2_y,FTRD_part2_y,TOV%_part2_y,TOV%D_part2_y,OREB%_part2_y,DREB%_part2_y,OP OREB%_part2_y,OP DREB%_part2_y,RAW T_part2_y,2PT%_part2_y,2PT%D_part2_y,3PT%_part2_y,3PT%D_part2_y,BLK%_part2_y,BLKED%_part2_y,AST%_part2_y,OP AST%_part2_y,2PTR_part2_y,3PTR_part2_y,2PTRD_part2_y,3PTRD_part2_y,BADJ T_part2_y,AVG HGT_part2_y,EFF HGT_part2_y,EXP_part2_y,TALENT_part2_y,FT%_part2_y,OP FT%_part2_y,PPPO_part2_y,PPPD_part2_y,ELITE SOS_part2_y,WAB_part2_y,BADJ EM RANK_part2_y,BADJ O RANK_part2_y,BADJ D RANK_part2_y,BARTHAG RANK_part2_y,EFG% RANK_part2_y,EFGD% RANK_part2_y,FTR RANK_part2_y,FTRD RANK_part2_y,TOV% RANK_part2_y,TOV%D RANK_part2_y,OREB% RANK_part2_y,DREB% RANK_part2_y,OP OREB% RANK_part2_y,OP DREB% RANK_part2_y,RAW T RANK_part2_y,2PT% RANK_part2_y,2PT%D RANK_part2_y,3PT% RANK_part2_y,3PT%D RANK_part2_y,BLK% RANK_part2_y,BLKED% RANK_part2_y,AST% RANK_part2_y,OP AST% RANK_part2_y,2PTR RANK_part2_y,3PTR RANK_part2_y,2PTRD RANK_part2_y,3PTRD RANK_part2_y,BADJT RANK_part2_y,AVG HGT RANK_part2_y,EFF HGT RANK_part2_y,EXP RANK_part2_y,TALENT RANK_part2_y,FT% RANK_part2_y,OP FT% RANK_part2_y,PPPO RANK_part2_y,PPPD RANK_part2_y,ELITE SOS RANK_part2_y,YEAR_part2_x.2,TEAM ID_part2_x.1,TEAM_part2_x.2,SEED_part2_x.2,ROUND_part2_x.2,BADJ EM_part2_x.1,BADJ O_part2_x.1,BADJ D_part2_x.1,BARTHAG_part2_x.1,GAMES_part2_x.1,W_part2_x.1,L_part2_x.1,WIN%_part2_x.1,EFG%_part2_x.1,EFG%D_part2_x.1,FTR_part2_x.1,FTRD_part2_x.1,TOV%_part2_x.1,TOV%D_part2_x.1,OREB%_part2_x.1,DREB%_part2_x.1,OP OREB%_part2_x.1,OP DREB%_part2_x.1,RAW T_part2_x.1,2PT%_part2_x.1,2PT%D_part2_x.1,3PT%_part2_x.1,3PT%D_part2_x.1,BLK%_part2_x.1,BLKED%_part2_x.1,AST%_part2_x.1,OP AST%_part2_x.1,2PTR_part2_x.1,3PTR_part2_x.1,2PTRD_part2_x.1,3PTRD_part2_x.1,BADJ T_part2_x.1,AVG HGT_part2_x.1,EFF HGT_part2_x.1,EXP_part2_x.1,TALENT_part2_x.1,FT%_part2_x.1,OP FT%_part2_x.1,PPPO_part2_x.1,PPPD_part2_x.1,ELITE SOS_part2_x.1,WAB_part2_x.1,BADJ EM RANK_part2_x.1,BADJ O RANK_part2_x.1,BADJ D RANK_part2_x.1,BARTHAG RANK_part2_x.1,EFG% RANK_part2_x.1,EFGD% RANK_part2_x.1,FTR RANK_part2_x.1,FTRD RANK_part2_x.1,TOV% RANK_part2_x.1,TOV%D RANK_part2_x.1,OREB% RANK_part2_x.1,DREB% RANK_part2_x.1,OP OREB% RANK_part2_x.1,OP DREB% RANK_part2_x.1,RAW T RANK_part2_x.1,2PT% RANK_part2_x.1,2PT%D RANK_part2_x.1,3PT% RANK_part2_x.1,3PT%D RANK_part2_x.1,BLK% RANK_part2_x.1,BLKED% RANK_part2_x.1,AST% RANK_part2_x.1,OP AST% RANK_part2_x.1,2PTR RANK_part2_x.1,3PTR RANK_part2_x.1,2PTRD RANK_part2_x.1,3PTRD RANK_part2_x.1,BADJT RANK_part2_x.1,AVG HGT RANK_part2_x.1,EFF HGT RANK_part2_x.1,EXP RANK_part2_x.1,TALENT RANK_part2_x.1,FT% RANK_part2_x.1,OP FT% RANK_part2_x.1,PPPO RANK_part2_x.1,PPPD RANK_part2_x.1,ELITE SOS RANK_part2_x.1,YEAR_part2_y.2,TEAM ID_part2_y.1,TEAM_part2_y.2,SEED_part2_y.2,ROUND_part2_y.2,BADJ EM_part2_y.1,BADJ O_part2_y.1,BADJ D_part2_y.1,BARTHAG_part2_y.1,GAMES_part2_y.1,W_part2_y.1,L_part2_y.1,WIN%_part2_y.1,EFG%_part2_y.1,EFG%D_part2_y.1,FTR_part2_y.1,FTRD_part2_y.1,TOV%_part2_y.1,TOV%D_part2_y.1,OREB%_part2_y.1,DREB%_part2_y.1,OP OREB%_part2_y.1,OP DREB%_part2_y.1,RAW T_part2_y.1,2PT%_part2_y.1,2PT%D_part2_y.1,3PT%_part2_y.1,3PT%D_part2_y.1,BLK%_part2_y.1,BLKED%_part2_y.1,AST%_part2_y.1,OP AST%_part2_y.1,2PTR_part2_y.1,3PTR_part2_y.1,2PTRD_part2_y.1,3PTRD_part2_y.1,BADJ T_part2_y.1,AVG HGT_part2_y.1,EFF HGT_part2_y.1,EXP_part2_y.1,TALENT_part2_y.1,FT%_part2_y.1,OP FT%_part2_y.1,PPPO_part2_y.1,PPPD_part2_y.1,ELITE SOS_part2_y.1,WAB_part2_y.1,BADJ EM RANK_part2_y.1,BADJ O RANK_part2_y.1,BADJ D RANK_part2_y.1,BARTHAG RANK_part2_y.1,EFG% RANK_part2_y.1,EFGD% RANK_part2_y.1,FTR RANK_part2_y.1,FTRD RANK_part2_y.1,TOV% RANK_part2_y.1,TOV%D RANK_part2_y.1,OREB% RANK_part2_y.1,DREB% RANK_part2_y.1,OP OREB% RANK_part2_y.1,OP DREB% RANK_part2_y.1,RAW T RANK_part2_y.1,2PT% RANK_part2_y.1,2PT%D RANK_part2_y.1,3PT% RANK_part2_y.1,3PT%D RANK_part2_y.1,BLK% RANK_part2_y.1,BLKED% RANK_part2_y.1,AST% RANK_part2_y.1,OP AST% RANK_part2_y.1,2PTR RANK_part2_y.1,3PTR RANK_part2_y.1,2PTRD RANK_part2_y.1,3PTRD RANK_part2_y.1,BADJT RANK_part2_y.1,AVG HGT RANK_part2_y.1,EFF HGT RANK_part2_y.1,EXP RANK_part2_y.1,TALENT RANK_part2_y.1,FT% RANK_part2_y.1,OP FT% RANK_part2_y.1,PPPO RANK_part2_y.1,PPPD RANK_part2_y.1,ELITE SOS RANK_part2_y.1,YEAR_part2_x.3,TEAM_part2_x.3,SEED_part2_x.3,ROUND_part2_x.3,EASY DRAW_part2,TOUGH DRAW_part2,DARK HORSE_part2,UPSET ALERT_part2,CINDERELLA_part2,YEAR_part2_y.3,TEAM_part2_y.3,SEED_part2_y.3,ROUND_part2_y.3,POWER_part2,PATH_part2,DRAW_part2,WINS_part2,POOL VALUE_part2,POOL S-RANK_part2,NCAA S-RANK_part2,VAL Z-SCORE_part2,POWER-PATH_part2,YEAR_part2_x.4,CONF_part2_x,CONF ID_part2,QUAD NO_part2,QUAD ID_part2,TEAM ID_part2_x.2,TEAM_part2_x.4,SEED_part2_x.4,ROUND_part2_x.4,K TEMPO_part2,K TEMPO RANK_part2,KADJ T_part2,KADJ T RANK_part2,K OFF_part2,KO RANK_part2,KADJ O_part2,KADJ O RANK_part2,K DEF_part2,KD RANK_part2,KADJ D_part2,KADJ D RANK_part2,KADJ EM_part2,KADJ EM RANK_part2,BADJ EM_part2,BADJ O_part2,BADJ D_part2,BARTHAG_part2,GAMES_part2,W_part2,L_part2,WIN%_part2,EFG%_part2,EFG%D_part2,FTR_part2,FTRD_part2,TOV%_part2,TOV%D_part2,OREB%_part2,DREB%_part2,OP OREB%_part2,OP DREB%_part2,RAW T_part2,2PT%_part2,2PT%D_part2,3PT%_part2,3PT%D_part2,BLK%_part2,BLKED%_part2,AST%_part2,OP AST%_part2,2PTR_part2,3PTR_part2,2PTRD_part2,3PTRD_part2,BADJ T_part2,AVG HGT_part2,EFF HGT_part2,EXP_part2,TALENT_part2,FT%_part2,OP FT%_part2,PPPO_part2,PPPD_part2,ELITE SOS_part2,WAB_part2,BADJ EM RANK_part2,BADJ O RANK_part2,BADJ D RANK_part2,BARTHAG RANK_part2,EFG% RANK_part2,EFGD% RANK_part2,FTR RANK_part2,FTRD RANK_part2,TOV% RANK_part2,TOV%D RANK_part2,OREB% RANK_part2,DREB% RANK_part2,OP OREB% RANK_part2,OP DREB% RANK_part2,RAW T RANK_part2,2PT% RANK_part2,2PT%D RANK_part2,3PT% RANK_part2,3PT%D RANK_part2,BLK% RANK_part2,BLKED% RANK_part2,AST% RANK_part2,OP AST% RANK_part2,2PTR RANK_part2,3PTR RANK_part2,2PTRD RANK_part2,3PTRD RANK_part2,BADJT RANK_part2,AVG HGT RANK_part2,EFF HGT RANK_part2,EXP RANK_part2,TALENT RANK_part2,FT% RANK_part2,OP FT% RANK_part2,PPPO RANK_part2,PPPD RANK_part2,ELITE SOS RANK_part2,YEAR_part2_y.4,TEAM_part2_y.4,SEED_part2_y.4,ROUND_part2_y.4,PRESEASON KADJ EM RANK_part2,PRESEASON KADJ EM_part2,PRESEASON KADJ O_part2,PRESEASON KADJ O RANK_part2,PRESEASON KADJ D_part2,PRESEASON KADJ D RANK_part2,PRESEASON KADJ T_part2,PRESEASON KADJ T RANK_part2,KADJ EM RANK CHANGE_part2,KADJ EM CHANGE_part2,KADJ T RANK CHANGE_part2,YEAR_part2_x.5,TEAM_part2_x.5,SEED_part2_x.5,ROUND_part2_x.5,AP VOTES_part2_y,AP RANK_part2_y,RANK?_part2_y,YEAR_part2_y.5,TEAM_part2_y.5,R64_part2,R32_part2,S16_part2,E8_part2,F4_part2,FINALS_part2,YEAR_part2_x.6,TEAM_part2_x.6,SEED_part2_y.5,ROUND_part2_y.5,NET RPI_part2,RESUME_part2,WAB RANK_part2,ELO_part2,B POWER_part2,Q1 W_part2,Q2 W_part2,Q1 PLUS Q2 W_part2,Q3 Q4 L_part2,PLUS 500_part2,R SCORE_part2,BID TYPE_part2,YEAR_part2_y.6,TEAM ID_part2_y.2,TEAM_part2_y.6,CONF_part2_y,DUNKS FG%_part2,DUNKS SHARE_part2,DUNKS FG%D_part2,DUNKS D SHARE_part2,CLOSE TWOS FG%_part2,CLOSE TWOS SHARE_part2,CLOSE TWOS FG%D_part2,CLOSE TWOS D SHARE_part2,FARTHER TWOS FG%_part2,FARTHER TWOS SHARE_part2,FARTHER TWOS FG%D_part2,FARTHER TWOS D SHARE_part2,THREES FG%_part2,THREES SHARE_part2,THREES FG%D_part2,THREES D SHARE_part2,DUNKS FG% RANK_part2,DUNKS SHARE RANK_part2,DUNKS FG%D RANK_part2,DUNKS D SHARE RANK_part2,CLOSE TWOS FG% RANK_part2,CLOSE TWOS SHARE RANK_part2,CLOSE TWOS FG%D RANK_part2,CLOSE TWOS D SHARE RANK_part2,FARTHER TWOS FG% RANK_part2,FARTHER TWOS SHARE RANK_part2,FARTHER TWOS FG%D RANK_part2,FARTHER TWOS D SHARE RANK_part2,THREES FG% RANK_part2,THREES SHARE RANK_part2,THREES FG%D RANK_part2,THREES D SHARE RANK_part2,YEAR_part2_x.7,TEAM_part2_x.7,SEED_part2_x.6,ROUND_part2_x.6,TR RANK_part2_x,TR RATING_part2_x,V 1-25 WINS_part2_x,V 1-25 LOSS_part2_x,V 26-50 WINS_part2_x,V 26-50 LOSS_part2_x,V 51-100 WINS_part2_x,V 51-100 LOSS_part2_x,HI_part2_x,LO_part2_x,LAST_part2_x,YEAR_part2_y.7,TEAM_part2_y.7,SEED_part2_y.6,ROUND_part2_y.6,TR RANK_part2_y,TR RATING_part2_y,V 1-25 WINS_part2_y,V 1-25 LOSS_part2_y,V 26-50 WINS_part2_y,V 26-50 LOSS_part2_y,V 51-100 WINS_part2_y,V 51-100 LOSS_part2_y,HI_part2_y,LO_part2_y,LAST_part2_y,YEAR_part2_x.8,TEAM_part2_x.8,SEED_part2_x.7,ROUND_part2_x.7,TR RANK_part2_x.1,TR RATING_part2_x.1,V 1-25 WINS_part2_x.1,V 1-25 LOSS_part2_x.1,V 26-50 WINS_part2_x.1,V 26-50 LOSS_part2_x.1,V 51-100 WINS_part2_x.1,V 51-100 LOSS_part2_x.1,HI_part2_x.1,LO_part2_x.1,LAST_part2_x.1,YEAR_part2_y.8,TEAM_part2_y.8,SEED_part2_y.7,ROUND_part2_y.7,TR RANK_part2_y.1,TR RATING_part2_y.1,V 1-25 WINS_part2_y.1,V 1-25 LOSS_part2_y.1,V 26-50 WINS_part2_y.1,V 26-50 LOSS_part2_y.1,V 51-100 WINS_part2_y.1,V 51-100 LOSS_part2_y.1,HI_part2_y.1,LO_part2_y.1,LAST_part2_y.1,SOS RANK_part2,SOS RATING_part2,SOS HI_part2,SOS LO_part2,SOS LAST_part2,LUCK RANK_part2,LUCK RATING_part2,LUCK V 1-25 WINS_part2,LUCK V 1-25 LOSS_part2,LUCK V 26-50 WINS_part2,LUCK V 26-50 LOSS_part2,LUCK V 51-100 WINS_part2,LUCK V 51-100 LOSS_part2,LUCK HI_part2,LUCK LO_part2,LUCK LAST_part2,CONSISTENCY RANK_part2,CONSISTENCY TR RATING_part2,CONSISTENCY V 1-25 WINS_part2,CONSISTENCY V 1-25 LOSS_part2,CONSISTENCY V 26-50 WINS_part2,CONSISTENCY V 26-50 LOSS_part2,CONSISTENCY V 51-100 WINS_part2,CONSISTENCY V 51-100 LOSS_part2,CONSISTENCY HI_part2,CONSISTENCY LO_part2,CONSISTENCY LAST_part2,YEAR_part2_x.9,BY YEAR NO_part2_x,BY ROUND NO_part2_x,TEAM_part2_x.9,SEED_part2_x.8,ROUND_part2_x.8,COLLEGE CITY_part2,COLLEGE STATE_part2,COLLEGE LOCATION_part2,COLLEGE TIME ZONE_part2,COLLEGE TIME ZONE VALUE_part2,DAYLIGHT SAVINGS TIME_part2,COLLEGE LATITUDE_part2,COLLEGE LONGITUDE_part2,GAME CITY_part2,GAME STATE_part2,GAME LOCATION_part2,GAME TIME ZONE_part2,GAME TIME ZONE VALUE_part2,DAYLIGHT SAVINGS TIME.1_part2,GAME LATITUDE_part2,GAME LONGITUDE_part2,TIME ZONE COMBINATION_part2,DIRECTION_part2,LONGITUDE DIFF_part2,TIME ZONES CROSSED_part2,TIME ZONES CROSSED VALUE_part2,DISTANCE (KM)_part2,DISTANCE (MI)_part2,YEAR_part2_y.9,BY YEAR NO_part2_y,BY ROUND NO_part2_y,TEAM_part2_y.9,SEED_part2_y.8,ROUND_part2_y.8,CURRENT ROUND_part2_x,SCORE_part2,YEAR_part2_x.10,BY YEAR NO_part2,BY ROUND NO_part2,TEAM_part2_x.10,SEED_part2_x.9,ROUND_part2_x.9,CURRENT ROUND_part2_y,YEAR_part2_y.10,TEAM_part2_y.10,SEED_part2_y.9,ROUND_part2_y.9,Z RATING_part2,Z RATING RANK_part2
0,2025.0,1147.0,Akron,13.0,0.0,6.277529,0.567429,6.844958,4.509381,1.703296,74.0,154.0,72.497815,17.0,161.0,0.593750,0.437500,19.0,14.0,56.0,30.0,28.0,42.0,56.0,46.0,56.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025.0,2.0,Akron,13.0,0.0,4.7,108.6,103.9,0.625,18.0,12.0,6.0,66.666667,53.6,49.9,26.9,31.7,17.9,17.5,31.0,71.2,28.8,69.0,73.6,53.4,50.7,35.9,32.4,9.7,8.0,55.4,46.7,56.9,43.1,63.0,37.0,73.0,75.063,77.508,2.383,16.228,76.6,71.7,1.096,1.035,14.146,-2.7,110.0,124.0,121.0,110.0,38.0,92.0,305.0,111.0,191.0,117.0,126.0,91.0,91.0,126.0,6.0,56.0,125.0,62.0,87.0,116.0,38.0,54.0,30.0,282.0,86.0,255.0,112.0,10.0,361.0,364.0,73.0,149.0,48.0,143.0,55.0,54.0,307.0,2025.0,2.0,Akron,13.0,0.0,6.2,109.6,103.4,0.661,12.0,8.0,4.0,66.666667,54.3,48.8,25.8,31.7,18.3,15.4,30.8,73.1,26.9,69.2,74.0,54.6,50.8,35.9,30.3,9.6,9.1,57.1,48.5,57.7,42.3,61.9,38.1,73.7,75.063,77.508,2.383,16.228,78.2,70.6,1.096,1.032,16.284,-1.5,97.0,108.0,103.0,96.0,34.0,52.0,315.0,112.0,217.0,245.0,122.0,42.0,42.0,122.0,5.0,33.0,120.0,68.0,30.0,121.0,91.0,33.0,59.0,267.0,100.0,212.0,154.0,6.0,361.0,364.0,73.0,149.0,34.0,96.0,49.0,50.0,283.0,2025.0,2.0,Akron,13.0,0.0,9.1,119.1,110.0,0.714,14.0,14.0,0.0,100.0,57.8,49.0,26.7,36.4,14.8,16.7,36.2,70.8,29.2,63.8,70.8,59.3,50.5,37.4,31.2,9.9,5.5,62.2,42.1,51.7,48.3,60.6,39.4,70.6,75.063,77.508,2.383,16.228,72.7,74.4,1.235,1.058,4.119,0.8,95.0,29.0,249.0,101.0,26.0,168.0,339.0,305.0,80.0,254.0,45.0,211.0,211.0,45.0,54.0,20.0,228.0,68.0,96.0,181.0,21.0,53.0,54.0,344.0,22.0,148.0,219.0,60.0,361.0,364.0,73.0,149.0,181.0,278.0,10.0,252.0,241.0,2025.0,2.0,Akron,13.0,0.0,2.0,106.8,104.8,0.554,6.0,4.0,2.0,66.666667,52.1,52.4,29.1,31.5,17.2,22.0,31.4,66.7,33.3,68.6,72.8,50.7,50.4,35.9,37.4,9.9,5.7,51.8,42.9,55.4,44.6,65.4,34.6,71.6,75.063,77.508,2.383,16.228,73.9,74.1,1.096,1.041,9.868,-1.2,150.0,151.0,183.0,151.0,101.0,248.0,246.0,152.0,201.0,32.0,136.0,285.0,285.0,136.0,29.0,156.0,202.0,87.0,286.0,134.0,77.0,147.0,80.0,286.0,79.0,262.0,105.0,38.0,361.0,364.0,73.0,149.0,146.0,237.0,90.0,181.0,221.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025.0,Akron,13.0,0.0,57.5,80.8,NaN,0.0,2.0,54.0,53.0,NaN,-23.3,2025.0,MAC,17.0,66.0,2.0,2.0,Akron,13.0,0.0,72.4588,15.0,71.4456,16.0,115.754,21.0,113.749,66.0,104.558,145.0,107.1760,183.0,6.57261,99.0,6.861,113.691,106.830,0.672,32.0,26.0,6.0,81.25000,55.4,49.5,26.8,33.7,16.6,17.2,33.3,71.0,29.0,66.7,72.4,55.8,50.6,36.6,31.9,9.8,7.0,58.5,44.7,54.6,45.4,62.0,38.0,71.176,75.063,77.508,2.383,16.228,74.9,73.0,1.156,1.045,9.759,-1.8,99.0,62.0,186.0,101.0,33.0,114.0,334.0,203.0,148.0,177.0,78.0,142.0,142.0,78.0,15.0,35.0,171.0,52.0,75.0,144.0,16.0,46.0,26.0,314.0,52.0,216.0,152.0,19.0,361.0,364.0,73.0,149.0,86.0,239.0,25.0,145.0,305.0,2025.0,Akron,13.0,0.0,130.0,2.94,102.6,143.0,99.7,126.0,69.7,291.0,31.0,3.63,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025.0,Akron,11.13%,3.59%,0.50%,0.19%,0.09%,0.05%,2025.0,Akron,13.0,0.0,91.0,112.0,65.0,45.0,104.0,0.0,1.0,1.0,3.0,21.0,0.02,Auto,2025.0,2.0,Akron,MAC,85.9,7.0,80.0,3.7,61.8,38.2,55.3,41.7,42.0,16.5,41.0,20.3,36.6,45.4,31.9,38.0,55.0,40.0,7.0,5.0,42.0,34.0,24.0,66.0,22.0,56.0,61.0,8.0,20.0,14.0,28.0,26.0,2025.0,Akron,13.0,0.0,95.0,5.6,0.0,1.0,0.0,0.0,1.0,1.0,29.0,213.0,95.0,2025.0,Akron,13.0,0.0,99.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,89.0,295.0,99.0,2025.0,Akron,13.0,0.0,134.0,2.9,0.0,1.0,0.0,0.0,0.0,1.0,37.0,350.0,128.0,2025.0,Akron,13.0,0.0,106.0,4.4,0.0,0.0,0.0,1.0,0.0,2.0,101.0,165.0,106.0,179.0,-2.5,60.0,260.0,183.0,21.0,2.7,4.0,0.0,3.0,1.0,2.0,1.0,21.0,339.0,40.0,109.0,9.6,0.0,0.0,0.0,0.0,3.0,0.0,12.0,339.0,118.0,2025.0,2117.0,2121.0,Akron,13.0,64.0,Akron,Ohio,Akron Ohio,Eastern,6.0,True,41.081445,-81.519005,Seattle,Washington,Seattle Washington,Pacific,3.0,True,47.606209,-122.332071,Eastern Pacific,West,-40.813066,3.0,-3.0,3285.509950,2041.521235,2025.0,2117.0,2121.0,Akron,13.0,64.0,64.0,NaN,2025.0,2117.0,2121.0,Akron,13.0,64.0,64.0,2025.0,Akron,13.0,0.0,10.16,53.0

In [7]:
# Print columns
print("Columns in KenPom and Reference Data:")
print(full_kenpom_df.columns.tolist())
print("\nColumns in Team Master Data:")
print(team_master.columns.tolist())

Columns in KenPom and Reference Data:
['Season', 'TeamName', 'eFGPct_off', 'RankeFGPct_off', 'TOPct_off', 'RankTOPct_off', 'ORPct_off', 'RankORPct_off', 'FTRate_off', 'RankFTRate_off', 'eFGPct_def', 'RankeFGPct_def', 'TOPct_def', 'RankTOPct_def', 'ORPct_def', 'RankORPct_def', 'FTRate_def', 'RankFTRate_def', 'Conference_extra', 'Adjusted Temo_extra', 'Adjusted Tempo Rank_extra', 'Raw Tempo_extra', 'Raw Tempo Rank_extra', 'Adjusted Offensive Efficiency_extra', 'Adjusted Offensive Efficiency Rank_extra', 'Raw Offensive Efficiency_extra', 'Raw Offensive Efficiency Rank_extra', 'Adjusted Defensive Efficiency_extra', 'Adjusted Defensive Efficiency Rank_extra', 'Raw Defensive Efficiency_extra', 'Raw Defensive Efficiency Rank_extra', 'Avg Possession Length (Offense)_extra', 'Avg Possession Length (Offense) Rank_extra', 'Avg Possession Length (Defense)_extra', 'Avg Possession Length (Defense) Rank_extra', 'AvgHeight_extra', 'RankAvgHeight_extra', 'CenterHeight_extra', 'RankCenterHeight_extra', 'PFHeight_extra', 'RankPFHeight_extra', 'SFHeight_extra', 'RankSFHeight_extra', 'SGHeight_extra', 'RankSGHeight_extra', 'PGHeight_extra', 'RankPGHeight_extra', 'EffectiveHeight_extra', 'RankEffectiveHeight_extra', 'Experience_extra', 'RankExperience_extra', 'Bench_extra', 'BenchRank_extra', 'CenterPts_extra', 'RankCenterPts_extra', 'PFPts_extra', 'RankPFPts_extra', 'SFPts_extra', 'RankSFPts_extra', 'SGPts_extra', 'RankSGPts_extra', 'PGPts_extra', 'RankPGPts_extra', 'CenterOR_extra', 'RankCenterOR_extra', 'PFOR_extra', 'RankPFOR_extra', 'SFOR_extra', 'RankSFOR_extra', 'SGOR_extra', 'RankSGOR_extra', 'PGOR_extra', 'RankPGOR_extra', 'CenterDR_extra', 'RankCenterDR_extra', 'PFDR_extra', 'RankPFDR_extra', 'SFDR_extra', 'RankSFDR_extra', 'SGDR_extra', 'RankSGDR_extra', 'PGDR_extra', 'RankPGDR_extra', 'FG2Pct_extra', 'RankFG2Pct_extra', 'FG3Pct_extra', 'RankFG3Pct_extra', 'FTPct_extra', 'RankFTPct_extra', 'BlockPct_extra', 'RankBlockPct_extra', 'OppFG2Pct_extra', 'RankOppFG2Pct_extra', 'OppFG3Pct_extra', 'RankOppFG3Pct_extra', 'OppFTPct_extra', 'RankOppFTPct_extra', 'OppBlockPct_extra', 'RankOppBlockPct_extra', 'FG3Rate_extra', 'RankFG3Rate_extra', 'OppFG3Rate_extra', 'RankOppFG3Rate_extra', 'ARate_extra', 'RankARate_extra', 'OppARate_extra', 'RankOppARate_extra', 'StlRate_extra', 'RankStlRate_extra', 'OppStlRate_extra', 'RankOppStlRate_extra', 'DFP_extra', 'NSTRate_extra', 'RankNSTRate_extra', 'OppNSTRate_extra', 'RankOppNSTRate_extra', 'OffFT_extra', 'RankOffFT_extra', 'Off2PtFG_extra', 'RankOff2PtFG_extra', 'Off3PtFG_extra', 'RankOff3PtFG_extra', 'DefFT_extra', 'RankDefFT_extra', 'Def2PtFG_extra', 'RankDef2PtFG_extra', 'Def3PtFG_extra', 'RankDef3PtFG_extra', 'Tempo_extra_x', 'RankTempo_extra_x', 'AdjTempo_extra_x', 'RankAdjTempo_extra_x', 'OE_extra_x', 'RankOE_extra_x', 'AdjOE_extra_x', 'RankAdjOE_extra_x', 'DE_extra_x', 'RankDE_extra_x', 'AdjDE_extra_x', 'RankAdjDE_extra_x', 'AdjEM_extra_x', 'RankAdjEM_extra_x', 'Seed_extra', 'Tempo_extra_y', 'RankTempo_extra_y', 'AdjTempo_extra_y', 'RankAdjTempo_extra_y', 'OE_extra_y', 'RankOE_extra_y', 'AdjOE_extra_y', 'RankAdjOE_extra_y', 'DE_extra_y', 'RankDE_extra_y', 'AdjDE_extra_y', 'RankAdjDE_extra_y', 'AdjEM_extra_y', 'RankAdjEM_extra_y', 'Seed_ref', 'Region_ref', 'Post-Season Tournament_ref', 'Post-Season Tournament Sorting Index_ref', 'Vulnerable Top 2 Seed?_ref', 'Tournament Winner?_ref', 'Tournament Championship?_ref', 'Final Four?_ref', 'Top 12 in AP Top 25 During Week 6?_ref', 'Conference', 'Mapped Conference Name', 'Mapped ESPN Team Name']

Columns in Team Master Data:
['YEAR', 'TEAM NO', 'TEAM', 'SEED', 'ROUND', 'O RATE', 'D RATE', 'RELATIVE RATING', 'OPPONENT ADJUST', 'PACE ADJUST', 'O RATE RANK', 'D RATE RANK', 'TRUE TEMPO', 'TRUE TEMPO RANK', 'HOME RANK', 'KILL SHOTS PER GAME', 'KILL SHOTS CONCEDED PER GAME', 'TOTAL KILL SHOTS', 'TOTAL KILL SHOTS CONCEDED', 'RELATIVE RATING RANK', 'OPPONENT ADJUST RANK', 'PACE ADJUST RANK', 'KILL SHOTS PER GAME RANK', 'KILL SHOTS CONCEDED PER GAME RANK', 'TOTAL KILL SHOTS RANK', 'TOTAL KILL SHOTS CONCEDED RANK', 'YEAR_part2_x', 'TEAM_part2_x', 'SEED_part2_x', 'ROUND_part2_x', 'POWER RATING_part2', 'POWER RATING RANK_part2', 'YEAR_part2_y', 'TEAM_part2_y', 'SEED_part2_y', 'ROUND_part2_y', 'AP VOTES_part2_x', 'AP RANK_part2_x', 'RANK?_part2_x', 'YEAR_part2_x.1', 'TEAM ID_part2_x', 'TEAM_part2_x.1', 'SEED_part2_x.1', 'ROUND_part2_x.1', 'BADJ EM_part2_x', 'BADJ O_part2_x', 'BADJ D_part2_x', 'BARTHAG_part2_x', 'GAMES_part2_x', 'W_part2_x', 'L_part2_x', 'WIN%_part2_x', 'EFG%_part2_x', 'EFG%D_part2_x', 'FTR_part2_x', 'FTRD_part2_x', 'TOV%_part2_x', 'TOV%D_part2_x', 'OREB%_part2_x', 'DREB%_part2_x', 'OP OREB%_part2_x', 'OP DREB%_part2_x', 'RAW T_part2_x', '2PT%_part2_x', '2PT%D_part2_x', '3PT%_part2_x', '3PT%D_part2_x', 'BLK%_part2_x', 'BLKED%_part2_x', 'AST%_part2_x', 'OP AST%_part2_x', '2PTR_part2_x', '3PTR_part2_x', '2PTRD_part2_x', '3PTRD_part2_x', 'BADJ T_part2_x', 'AVG HGT_part2_x', 'EFF HGT_part2_x', 'EXP_part2_x', 'TALENT_part2_x', 'FT%_part2_x', 'OP FT%_part2_x', 'PPPO_part2_x', 'PPPD_part2_x', 'ELITE SOS_part2_x', 'WAB_part2_x', 'BADJ EM RANK_part2_x', 'BADJ O RANK_part2_x', 'BADJ D RANK_part2_x', 'BARTHAG RANK_part2_x', 'EFG% RANK_part2_x', 'EFGD% RANK_part2_x', 'FTR RANK_part2_x', 'FTRD RANK_part2_x', 'TOV% RANK_part2_x', 'TOV%D RANK_part2_x', 'OREB% RANK_part2_x', 'DREB% RANK_part2_x', 'OP OREB% RANK_part2_x', 'OP DREB% RANK_part2_x', 'RAW T RANK_part2_x', '2PT% RANK_part2_x', '2PT%D RANK_part2_x', '3PT% RANK_part2_x', '3PT%D RANK_part2_x', 'BLK% RANK_part2_x', 'BLKED% RANK_part2_x', 'AST% RANK_part2_x', 'OP AST% RANK_part2_x', '2PTR RANK_part2_x', '3PTR RANK_part2_x', '2PTRD RANK_part2_x', '3PTRD RANK_part2_x', 'BADJT RANK_part2_x', 'AVG HGT RANK_part2_x', 'EFF HGT RANK_part2_x', 'EXP RANK_part2_x', 'TALENT RANK_part2_x', 'FT% RANK_part2_x', 'OP FT% RANK_part2_x', 'PPPO RANK_part2_x', 'PPPD RANK_part2_x', 'ELITE SOS RANK_part2_x', 'YEAR_part2_y.1', 'TEAM ID_part2_y', 'TEAM_part2_y.1', 'SEED_part2_y.1', 'ROUND_part2_y.1', 'BADJ EM_part2_y', 'BADJ O_part2_y', 'BADJ D_part2_y', 'BARTHAG_part2_y', 'GAMES_part2_y', 'W_part2_y', 'L_part2_y', 'WIN%_part2_y', 'EFG%_part2_y', 'EFG%D_part2_y', 'FTR_part2_y', 'FTRD_part2_y', 'TOV%_part2_y', 'TOV%D_part2_y', 'OREB%_part2_y', 'DREB%_part2_y', 'OP OREB%_part2_y', 'OP DREB%_part2_y', 'RAW T_part2_y', '2PT%_part2_y', '2PT%D_part2_y', '3PT%_part2_y', '3PT%D_part2_y', 'BLK%_part2_y', 'BLKED%_part2_y', 'AST%_part2_y', 'OP AST%_part2_y', '2PTR_part2_y', '3PTR_part2_y', '2PTRD_part2_y', '3PTRD_part2_y', 'BADJ T_part2_y', 'AVG HGT_part2_y', 'EFF HGT_part2_y', 'EXP_part2_y', 'TALENT_part2_y', 'FT%_part2_y', 'OP FT%_part2_y', 'PPPO_part2_y', 'PPPD_part2_y', 'ELITE SOS_part2_y', 'WAB_part2_y', 'BADJ EM RANK_part2_y', 'BADJ O RANK_part2_y', 'BADJ D RANK_part2_y', 'BARTHAG RANK_part2_y', 'EFG% RANK_part2_y', 'EFGD% RANK_part2_y', 'FTR RANK_part2_y', 'FTRD RANK_part2_y', 'TOV% RANK_part2_y', 'TOV%D RANK_part2_y', 'OREB% RANK_part2_y', 'DREB% RANK_part2_y', 'OP OREB% RANK_part2_y', 'OP DREB% RANK_part2_y', 'RAW T RANK_part2_y', '2PT% RANK_part2_y', '2PT%D RANK_part2_y', '3PT% RANK_part2_y', '3PT%D RANK_part2_y', 'BLK% RANK_part2_y', 'BLKED% RANK_part2_y', 'AST% RANK_part2_y', 'OP AST% RANK_part2_y', '2PTR RANK_part2_y', '3PTR RANK_part2_y', '2PTRD RANK_part2_y', '3PTRD RANK_part2_y', 'BADJT RANK_part2_y', 'AVG HGT RANK_part2_y', 'EFF HGT RANK_part2_y', 'EXP RANK_part2_y', 'TALENT RANK_part2_y', 'FT% RANK_part2_y', 'OP FT% RANK_part2_y', 'PPPO RANK_part2_y', 'PPPD RANK_part2_y', 'ELITE SOS RANK_part2_y', 'YEAR_part2_x.2', 'TEAM ID_part2_x.1', 'TEAM_part2_x.2', 'SEED_part2_x.2', 'ROUND_part2_x.2', 'BADJ EM_part2_x.1', 'BADJ O_part2_x.1', 'BADJ D_part2_x.1', 'BARTHAG_part2_x.1', 'GAMES_part2_x.1', 'W_part2_x.1', 'L_part2_x.1', 'WIN%_part2_x.1', 'EFG%_part2_x.1', 'EFG%D_part2_x.1', 'FTR_part2_x.1', 'FTRD_part2_x.1', 'TOV%_part2_x.1', 'TOV%D_part2_x.1', 'OREB%_part2_x.1', 'DREB%_part2_x.1', 'OP OREB%_part2_x.1', 'OP DREB%_part2_x.1', 'RAW T_part2_x.1', '2PT%_part2_x.1', '2PT%D_part2_x.1', '3PT%_part2_x.1', '3PT%D_part2_x.1', 'BLK%_part2_x.1', 'BLKED%_part2_x.1', 'AST%_part2_x.1', 'OP AST%_part2_x.1', '2PTR_part2_x.1', '3PTR_part2_x.1', '2PTRD_part2_x.1', '3PTRD_part2_x.1', 'BADJ T_part2_x.1', 'AVG HGT_part2_x.1', 'EFF HGT_part2_x.1', 'EXP_part2_x.1', 'TALENT_part2_x.1', 'FT%_part2_x.1', 'OP FT%_part2_x.1', 'PPPO_part2_x.1', 'PPPD_part2_x.1', 'ELITE SOS_part2_x.1', 'WAB_part2_x.1', 'BADJ EM RANK_part2_x.1', 'BADJ O RANK_part2_x.1', 'BADJ D RANK_part2_x.1', 'BARTHAG RANK_part2_x.1', 'EFG% RANK_part2_x.1', 'EFGD% RANK_part2_x.1', 'FTR RANK_part2_x.1', 'FTRD RANK_part2_x.1', 'TOV% RANK_part2_x.1', 'TOV%D RANK_part2_x.1', 'OREB% RANK_part2_x.1', 'DREB% RANK_part2_x.1', 'OP OREB% RANK_part2_x.1', 'OP DREB% RANK_part2_x.1', 'RAW T RANK_part2_x.1', '2PT% RANK_part2_x.1', '2PT%D RANK_part2_x.1', '3PT% RANK_part2_x.1', '3PT%D RANK_part2_x.1', 'BLK% RANK_part2_x.1', 'BLKED% RANK_part2_x.1', 'AST% RANK_part2_x.1', 'OP AST% RANK_part2_x.1', '2PTR RANK_part2_x.1', '3PTR RANK_part2_x.1', '2PTRD RANK_part2_x.1', '3PTRD RANK_part2_x.1', 'BADJT RANK_part2_x.1', 'AVG HGT RANK_part2_x.1', 'EFF HGT RANK_part2_x.1', 'EXP RANK_part2_x.1', 'TALENT RANK_part2_x.1', 'FT% RANK_part2_x.1', 'OP FT% RANK_part2_x.1', 'PPPO RANK_part2_x.1', 'PPPD RANK_part2_x.1', 'ELITE SOS RANK_part2_x.1', 'YEAR_part2_y.2', 'TEAM ID_part2_y.1', 'TEAM_part2_y.2', 'SEED_part2_y.2', 'ROUND_part2_y.2', 'BADJ EM_part2_y.1', 'BADJ O_part2_y.1', 'BADJ D_part2_y.1', 'BARTHAG_part2_y.1', 'GAMES_part2_y.1', 'W_part2_y.1', 'L_part2_y.1', 'WIN%_part2_y.1', 'EFG%_part2_y.1', 'EFG%D_part2_y.1', 'FTR_part2_y.1', 'FTRD_part2_y.1', 'TOV%_part2_y.1', 'TOV%D_part2_y.1', 'OREB%_part2_y.1', 'DREB%_part2_y.1', 'OP OREB%_part2_y.1', 'OP DREB%_part2_y.1', 'RAW T_part2_y.1', '2PT%_part2_y.1', '2PT%D_part2_y.1', '3PT%_part2_y.1', '3PT%D_part2_y.1', 'BLK%_part2_y.1', 'BLKED%_part2_y.1', 'AST%_part2_y.1', 'OP AST%_part2_y.1', '2PTR_part2_y.1', '3PTR_part2_y.1', '2PTRD_part2_y.1', '3PTRD_part2_y.1', 'BADJ T_part2_y.1', 'AVG HGT_part2_y.1', 'EFF HGT_part2_y.1', 'EXP_part2_y.1', 'TALENT_part2_y.1', 'FT%_part2_y.1', 'OP FT%_part2_y.1', 'PPPO_part2_y.1', 'PPPD_part2_y.1', 'ELITE SOS_part2_y.1', 'WAB_part2_y.1', 'BADJ EM RANK_part2_y.1', 'BADJ O RANK_part2_y.1', 'BADJ D RANK_part2_y.1', 'BARTHAG RANK_part2_y.1', 'EFG% RANK_part2_y.1', 'EFGD% RANK_part2_y.1', 'FTR RANK_part2_y.1', 'FTRD RANK_part2_y.1', 'TOV% RANK_part2_y.1', 'TOV%D RANK_part2_y.1', 'OREB% RANK_part2_y.1', 'DREB% RANK_part2_y.1', 'OP OREB% RANK_part2_y.1', 'OP DREB% RANK_part2_y.1', 'RAW T RANK_part2_y.1', '2PT% RANK_part2_y.1', '2PT%D RANK_part2_y.1', '3PT% RANK_part2_y.1', '3PT%D RANK_part2_y.1', 'BLK% RANK_part2_y.1', 'BLKED% RANK_part2_y.1', 'AST% RANK_part2_y.1', 'OP AST% RANK_part2_y.1', '2PTR RANK_part2_y.1', '3PTR RANK_part2_y.1', '2PTRD RANK_part2_y.1', '3PTRD RANK_part2_y.1', 'BADJT RANK_part2_y.1', 'AVG HGT RANK_part2_y.1', 'EFF HGT RANK_part2_y.1', 'EXP RANK_part2_y.1', 'TALENT RANK_part2_y.1', 'FT% RANK_part2_y.1', 'OP FT% RANK_part2_y.1', 'PPPO RANK_part2_y.1', 'PPPD RANK_part2_y.1', 'ELITE SOS RANK_part2_y.1', 'YEAR_part2_x.3', 'TEAM_part2_x.3', 'SEED_part2_x.3', 'ROUND_part2_x.3', 'EASY DRAW_part2', 'TOUGH DRAW_part2', 'DARK HORSE_part2', 'UPSET ALERT_part2', 'CINDERELLA_part2', 'YEAR_part2_y.3', 'TEAM_part2_y.3', 'SEED_part2_y.3', 'ROUND_part2_y.3', 'POWER_part2', 'PATH_part2', 'DRAW_part2', 'WINS_part2', 'POOL VALUE_part2', 'POOL S-RANK_part2', 'NCAA S-RANK_part2', 'VAL Z-SCORE_part2', 'POWER-PATH_part2', 'YEAR_part2_x.4', 'CONF_part2_x', 'CONF ID_part2', 'QUAD NO_part2', 'QUAD ID_part2', 'TEAM ID_part2_x.2', 'TEAM_part2_x.4', 'SEED_part2_x.4', 'ROUND_part2_x.4', 'K TEMPO_part2', 'K TEMPO RANK_part2', 'KADJ T_part2', 'KADJ T RANK_part2', 'K OFF_part2', 'KO RANK_part2', 'KADJ O_part2', 'KADJ O RANK_part2', 'K DEF_part2', 'KD RANK_part2', 'KADJ D_part2', 'KADJ D RANK_part2', 'KADJ EM_part2', 'KADJ EM RANK_part2', 'BADJ EM_part2', 'BADJ O_part2', 'BADJ D_part2', 'BARTHAG_part2', 'GAMES_part2', 'W_part2', 'L_part2', 'WIN%_part2', 'EFG%_part2', 'EFG%D_part2', 'FTR_part2', 'FTRD_part2', 'TOV%_part2', 'TOV%D_part2', 'OREB%_part2', 'DREB%_part2', 'OP OREB%_part2', 'OP DREB%_part2', 'RAW T_part2', '2PT%_part2', '2PT%D_part2', '3PT%_part2', '3PT%D_part2', 'BLK%_part2', 'BLKED%_part2', 'AST%_part2', 'OP AST%_part2', '2PTR_part2', '3PTR_part2', '2PTRD_part2', '3PTRD_part2', 'BADJ T_part2', 'AVG HGT_part2', 'EFF HGT_part2', 'EXP_part2', 'TALENT_part2', 'FT%_part2', 'OP FT%_part2', 'PPPO_part2', 'PPPD_part2', 'ELITE SOS_part2', 'WAB_part2', 'BADJ EM RANK_part2', 'BADJ O RANK_part2', 'BADJ D RANK_part2', 'BARTHAG RANK_part2', 'EFG% RANK_part2', 'EFGD% RANK_part2', 'FTR RANK_part2', 'FTRD RANK_part2', 'TOV% RANK_part2', 'TOV%D RANK_part2', 'OREB% RANK_part2', 'DREB% RANK_part2', 'OP OREB% RANK_part2', 'OP DREB% RANK_part2', 'RAW T RANK_part2', '2PT% RANK_part2', '2PT%D RANK_part2', '3PT% RANK_part2', '3PT%D RANK_part2', 'BLK% RANK_part2', 'BLKED% RANK_part2', 'AST% RANK_part2', 'OP AST% RANK_part2', '2PTR RANK_part2', '3PTR RANK_part2', '2PTRD RANK_part2', '3PTRD RANK_part2', 'BADJT RANK_part2', 'AVG HGT RANK_part2', 'EFF HGT RANK_part2', 'EXP RANK_part2', 'TALENT RANK_part2', 'FT% RANK_part2', 'OP FT% RANK_part2', 'PPPO RANK_part2', 'PPPD RANK_part2', 'ELITE SOS RANK_part2', 'YEAR_part2_y.4', 'TEAM_part2_y.4', 'SEED_part2_y.4', 'ROUND_part2_y.4', 'PRESEASON KADJ EM RANK_part2', 'PRESEASON KADJ EM_part2', 'PRESEASON KADJ O_part2', 'PRESEASON KADJ O RANK_part2', 'PRESEASON KADJ D_part2', 'PRESEASON KADJ D RANK_part2', 'PRESEASON KADJ T_part2', 'PRESEASON KADJ T RANK_part2', 'KADJ EM RANK CHANGE_part2', 'KADJ EM CHANGE_part2', 'KADJ T RANK CHANGE_part2', 'YEAR_part2_x.5', 'TEAM_part2_x.5', 'SEED_part2_x.5', 'ROUND_part2_x.5', 'AP VOTES_part2_y', 'AP RANK_part2_y', 'RANK?_part2_y', 'YEAR_part2_y.5', 'TEAM_part2_y.5', 'R64_part2', 'R32_part2', 'S16_part2', 'E8_part2', 'F4_part2', 'FINALS_part2', 'YEAR_part2_x.6', 'TEAM_part2_x.6', 'SEED_part2_y.5', 'ROUND_part2_y.5', 'NET RPI_part2', 'RESUME_part2', 'WAB RANK_part2', 'ELO_part2', 'B POWER_part2', 'Q1 W_part2', 'Q2 W_part2', 'Q1 PLUS Q2 W_part2', 'Q3 Q4 L_part2', 'PLUS 500_part2', 'R SCORE_part2', 'BID TYPE_part2', 'YEAR_part2_y.6', 'TEAM ID_part2_y.2', 'TEAM_part2_y.6', 'CONF_part2_y', 'DUNKS FG%_part2', 'DUNKS SHARE_part2', 'DUNKS FG%D_part2', 'DUNKS D SHARE_part2', 'CLOSE TWOS FG%_part2', 'CLOSE TWOS SHARE_part2', 'CLOSE TWOS FG%D_part2', 'CLOSE TWOS D SHARE_part2', 'FARTHER TWOS FG%_part2', 'FARTHER TWOS SHARE_part2', 'FARTHER TWOS FG%D_part2', 'FARTHER TWOS D SHARE_part2', 'THREES FG%_part2', 'THREES SHARE_part2', 'THREES FG%D_part2', 'THREES D SHARE_part2', 'DUNKS FG% RANK_part2', 'DUNKS SHARE RANK_part2', 'DUNKS FG%D RANK_part2', 'DUNKS D SHARE RANK_part2', 'CLOSE TWOS FG% RANK_part2', 'CLOSE TWOS SHARE RANK_part2', 'CLOSE TWOS FG%D RANK_part2', 'CLOSE TWOS D SHARE RANK_part2', 'FARTHER TWOS FG% RANK_part2', 'FARTHER TWOS SHARE RANK_part2', 'FARTHER TWOS FG%D RANK_part2', 'FARTHER TWOS D SHARE RANK_part2', 'THREES FG% RANK_part2', 'THREES SHARE RANK_part2', 'THREES FG%D RANK_part2', 'THREES D SHARE RANK_part2', 'YEAR_part2_x.7', 'TEAM_part2_x.7', 'SEED_part2_x.6', 'ROUND_part2_x.6', 'TR RANK_part2_x', 'TR RATING_part2_x', 'V 1-25 WINS_part2_x', 'V 1-25 LOSS_part2_x', 'V 26-50 WINS_part2_x', 'V 26-50 LOSS_part2_x', 'V 51-100 WINS_part2_x', 'V 51-100 LOSS_part2_x', 'HI_part2_x', 'LO_part2_x', 'LAST_part2_x', 'YEAR_part2_y.7', 'TEAM_part2_y.7', 'SEED_part2_y.6', 'ROUND_part2_y.6', 'TR RANK_part2_y', 'TR RATING_part2_y', 'V 1-25 WINS_part2_y', 'V 1-25 LOSS_part2_y', 'V 26-50 WINS_part2_y', 'V 26-50 LOSS_part2_y', 'V 51-100 WINS_part2_y', 'V 51-100 LOSS_part2_y', 'HI_part2_y', 'LO_part2_y', 'LAST_part2_y', 'YEAR_part2_x.8', 'TEAM_part2_x.8', 'SEED_part2_x.7', 'ROUND_part2_x.7', 'TR RANK_part2_x.1', 'TR RATING_part2_x.1', 'V 1-25 WINS_part2_x.1', 'V 1-25 LOSS_part2_x.1', 'V 26-50 WINS_part2_x.1', 'V 26-50 LOSS_part2_x.1', 'V 51-100 WINS_part2_x.1', 'V 51-100 LOSS_part2_x.1', 'HI_part2_x.1', 'LO_part2_x.1', 'LAST_part2_x.1', 'YEAR_part2_y.8', 'TEAM_part2_y.8', 'SEED_part2_y.7', 'ROUND_part2_y.7', 'TR RANK_part2_y.1', 'TR RATING_part2_y.1', 'V 1-25 WINS_part2_y.1', 'V 1-25 LOSS_part2_y.1', 'V 26-50 WINS_part2_y.1', 'V 26-50 LOSS_part2_y.1', 'V 51-100 WINS_part2_y.1', 'V 51-100 LOSS_part2_y.1', 'HI_part2_y.1', 'LO_part2_y.1', 'LAST_part2_y.1', 'SOS RANK_part2', 'SOS RATING_part2', 'SOS HI_part2', 'SOS LO_part2', 'SOS LAST_part2', 'LUCK RANK_part2', 'LUCK RATING_part2', 'LUCK V 1-25 WINS_part2', 'LUCK V 1-25 LOSS_part2', 'LUCK V 26-50 WINS_part2', 'LUCK V 26-50 LOSS_part2', 'LUCK V 51-100 WINS_part2', 'LUCK V 51-100 LOSS_part2', 'LUCK HI_part2', 'LUCK LO_part2', 'LUCK LAST_part2', 'CONSISTENCY RANK_part2', 'CONSISTENCY TR RATING_part2', 'CONSISTENCY V 1-25 WINS_part2', 'CONSISTENCY V 1-25 LOSS_part2', 'CONSISTENCY V 26-50 WINS_part2', 'CONSISTENCY V 26-50 LOSS_part2', 'CONSISTENCY V 51-100 WINS_part2', 'CONSISTENCY V 51-100 LOSS_part2', 'CONSISTENCY HI_part2', 'CONSISTENCY LO_part2', 'CONSISTENCY LAST_part2', 'YEAR_part2_x.9', 'BY YEAR NO_part2_x', 'BY ROUND NO_part2_x', 'TEAM_part2_x.9', 'SEED_part2_x.8', 'ROUND_part2_x.8', 'COLLEGE CITY_part2', 'COLLEGE STATE_part2', 'COLLEGE LOCATION_part2', 'COLLEGE TIME ZONE_part2', 'COLLEGE TIME ZONE VALUE_part2', 'DAYLIGHT SAVINGS TIME_part2', 'COLLEGE LATITUDE_part2', 'COLLEGE LONGITUDE_part2', 'GAME CITY_part2', 'GAME STATE_part2', 'GAME LOCATION_part2', 'GAME TIME ZONE_part2', 'GAME TIME ZONE VALUE_part2', 'DAYLIGHT SAVINGS TIME.1_part2', 'GAME LATITUDE_part2', 'GAME LONGITUDE_part2', 'TIME ZONE COMBINATION_part2', 'DIRECTION_part2', 'LONGITUDE DIFF_part2', 'TIME ZONES CROSSED_part2', 'TIME ZONES CROSSED VALUE_part2', 'DISTANCE (KM)_part2', 'DISTANCE (MI)_part2', 'YEAR_part2_y.9', 'BY YEAR NO_part2_y', 'BY ROUND NO_part2_y', 'TEAM_part2_y.9', 'SEED_part2_y.8', 'ROUND_part2_y.8', 'CURRENT ROUND_part2_x', 'SCORE_part2', 'YEAR_part2_x.10', 'BY YEAR NO_part2', 'BY ROUND NO_part2', 'TEAM_part2_x.10', 'SEED_part2_x.9', 'ROUND_part2_x.9', 'CURRENT ROUND_part2_y', 'YEAR_part2_y.10', 'TEAM_part2_y.10', 'SEED_part2_y.9', 'ROUND_part2_y.9', 'Z RATING_part2', 'Z RATING RANK_part2']

In [8]:
# Print shapes of dataframes
print(f"KenPom and Reference Data shape: {full_kenpom_df.shape}")
print(f"Team Master Data shape: {team_master.shape}")

KenPom and Reference Data shape: (16205, 169)
Team Master Data shape: (52203, 718)

# 2. Clean and Check Data

## Part 1

In [9]:
full_kenpom_df.head()

,Season,TeamName,eFGPct_off,RankeFGPct_off,TOPct_off,RankTOPct_off,ORPct_off,RankORPct_off,FTRate_off,RankFTRate_off,eFGPct_def,RankeFGPct_def,TOPct_def,RankTOPct_def,ORPct_def,RankORPct_def,FTRate_def,RankFTRate_def,Conference_extra,Adjusted Temo_extra,Adjusted Tempo Rank_extra,Raw Tempo_extra,Raw Tempo Rank_extra,Adjusted Offensive Efficiency_extra,Adjusted Offensive Efficiency Rank_extra,Raw Offensive Efficiency_extra,Raw Offensive Efficiency Rank_extra,Adjusted Defensive Efficiency_extra,Adjusted Defensive Efficiency Rank_extra,Raw Defensive Efficiency_extra,Raw Defensive Efficiency Rank_extra,Avg Possession Length (Offense)_extra,Avg Possession Length (Offense) Rank_extra,Avg Possession Length (Defense)_extra,Avg Possession Length (Defense) Rank_extra,AvgHeight_extra,RankAvgHeight_extra,CenterHeight_extra,RankCenterHeight_extra,PFHeight_extra,RankPFHeight_extra,SFHeight_extra,RankSFHeight_extra,SGHeight_extra,RankSGHeight_extra,PGHeight_extra,RankPGHeight_extra,EffectiveHeight_extra,RankEffectiveHeight_extra,Experience_extra,RankExperience_extra,Bench_extra,BenchRank_extra,CenterPts_extra,RankCenterPts_extra,PFPts_extra,RankPFPts_extra,SFPts_extra,RankSFPts_extra,SGPts_extra,RankSGPts_extra,PGPts_extra,RankPGPts_extra,CenterOR_extra,RankCenterOR_extra,PFOR_extra,RankPFOR_extra,SFOR_extra,RankSFOR_extra,SGOR_extra,RankSGOR_extra,PGOR_extra,RankPGOR_extra,CenterDR_extra,RankCenterDR_extra,PFDR_extra,RankPFDR_extra,SFDR_extra,RankSFDR_extra,SGDR_extra,RankSGDR_extra,PGDR_extra,RankPGDR_extra,FG2Pct_extra,RankFG2Pct_extra,FG3Pct_extra,RankFG3Pct_extra,FTPct_extra,RankFTPct_extra,BlockPct_extra,RankBlockPct_extra,OppFG2Pct_extra,RankOppFG2Pct_extra,OppFG3Pct_extra,RankOppFG3Pct_extra,OppFTPct_extra,RankOppFTPct_extra,OppBlockPct_extra,RankOppBlockPct_extra,FG3Rate_extra,RankFG3Rate_extra,OppFG3Rate_extra,RankOppFG3Rate_extra,ARate_extra,RankARate_extra,OppARate_extra,RankOppARate_extra,StlRate_extra,RankStlRate_extra,OppStlRate_extra,RankOppStlRate_extra,DFP_extra,NSTRate_extra,RankNSTRate_extra,OppNSTRate_extra,RankOppNSTRate_extra,OffFT_extra,RankOffFT_extra,Off2PtFG_extra,RankOff2PtFG_extra,Off3PtFG_extra,RankOff3PtFG_extra,DefFT_extra,RankDefFT_extra,Def2PtFG_extra,RankDef2PtFG_extra,Def3PtFG_extra,RankDef3PtFG_extra,Tempo_extra_x,RankTempo_extra_x,AdjTempo_extra_x,RankAdjTempo_extra_x,OE_extra_x,RankOE_extra_x,AdjOE_extra_x,RankAdjOE_extra_x,DE_extra_x,RankDE_extra_x,AdjDE_extra_x,RankAdjDE_extra_x,AdjEM_extra_x,RankAdjEM_extra_x,Seed_extra,Tempo_extra_y,RankTempo_extra_y,AdjTempo_extra_y,RankAdjTempo_extra_y,OE_extra_y,RankOE_extra_y,AdjOE_extra_y,RankAdjOE_extra_y,DE_extra_y,RankDE_extra_y,AdjDE_extra_y,RankAdjDE_extra_y,AdjEM_extra_y,RankAdjEM_extra_y,Seed_ref,Region_ref,Post-Season Tournament_ref,Post-Season Tournament Sorting Index_ref,Vulnerable Top 2 Seed?_ref,Tournament Winner?_ref,Tournament Championship?_ref,Final Four?_ref,Top 12 in AP Top 25 During Week 6?_ref,Conference,Mapped Conference Name,Mapped ESPN Team Name
0,2025,Abilene Christian,46.689148,332.0,20.740433,350.0,30.069238,178.0,37.155120,57.0,51.411290,211.0,24.010102,1.0,31.450720,263.0,51.276882,364.0,WAC,69.6,65.0,70.1,73.0,97.7,330.0,95.7,346.0,102.3,92.0,100.8,54.0,16.8,79.0,17.5,145.0,77.31,163.0,-0.37,209.0,-0.84,281.0,-0.23,226.0,0.68,95.0,1.31,67.0,-0.60,259.0,1.34123,253.0,34.05,103.0,23.57,63.0,23.58,52.0,23.82,59.0,12.66,362.0,16.37,298.0,30.57,272.0,29.91,104.0,22.05,77.0,7.76,284.0,9.71,129.0,19.37,343.0,26.10,87.0,22.05,86.0,16.78,161.0,15.70,122.0,47.826087,295.0,28.883495,355.0,71.947195,195.0,8.366534,226.0,52.589641,251.0,32.644628,107.0,69.200524,31.0,11.156686,317.0,25.260576,362.0,32.526882,15.0,51.566952,178.0,51.603499,178.0,0.142011,3.0,0.111754,317.0,NaN,9.565000,348.0,9.809005,12.0,22.256253,31.0,59.520163,3.0,18.223583,362.0,25.655977,1.0,51.311953,110.0,23.032070,360.0,70.0679,72.0,69.3532,67.0,95.6706,346.0,97.6324,328.0,100.773,60.0,102.0970,86.0,-4.46503,219.0,NaN,70.0679,73.0,69.6271,65.0,95.6706,346.0,97.6737,330.0,100.773,54.0,102.3350,92.0,-4.66102,221.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Slnd,Southland Conference (SLC),Abilene Christian
1,2025,Abilene Christian,46.689148,332.0,20.740433,350.0,30.069238,178.0,37.155120,57.0,51.411290,211.0,24.010102,1.0,31.450720,263.0,51.276882,364.0,WAC,69.6,65.0,70.1,73.0,97.7,330.0,95.7,346.0,102.3,92.0,100.8,54.0,16.8,79.0,17.5,145.0,77.31,163.0,-0.37,209.0,-0.84,281.0,-0.23,226.0,0.68,95.0,1.31,67.0,-0.60,259.0,1.34123,253.0,34.05,103.0,23.57,63.0,23.58,52.0,23.82,59.0,12.66,362.0,16.37,298.0,30.57,272.0,29.91,104.0,22.05,77.0,7.76,284.0,9.71,129.0,19.37,343.0,26.10,87.0,22.05,86.0,16.78,161.0,15.70,122.0,47.826087,295.0,28.883495,355.0,71.947195,195.0,8.366534,226.0,52.589641,251.0,32.644628,107.0,69.200524,31.0,11.156686,317.0,25.260576,362.0,32.526882,15.0,51.566952,178.0,51.603499,178.0,0.142011,3.0,0.111754,317.0,NaN,9.565000,348.0,9.809005,12.0,22.256253,31.0,59.520163,3.0,18.223583,362.0,25.655977,1.0,51.311953,110.0,23.032070,360.0,70.0679,72.0,69.3532,67.0,95.6706,346.0,97.6324,328.0,100.773,60.0,102.0970,86.0,-4.46503,219.0,NaN,70.0679,73.0,69.6271,65.0,95.6706,346.0,97.6737,330.0,100.773,54.0,102.3350,92.0,-4.66102,221.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WAC,Western Athletic Conference (WAC),Abilene Christian
2,2025,Air Force,50.092822,220.0,20.721288,348.0,22.736031,343.0,35.396040,108.0,54.635950,334.0,15.684864,279.0,29.064039,142.0,35.437998,242.0,MWC,64.6,325.0,64.7,335.0,98.9,312.0,95.3,347.0,111.7,272.0,113.1,335.0,19.8,357.0,17.0,46.0,78.18,46.0,1.08,75.0,-0.23,212.0,0.01,178.0,1.13,61.0,2.88,6.0,0.43,120.0,1.78985,166.0,28.89,255.0,26.40,18.0,22.02,92.0,18.77,217.0,19.57,225.0,13.19,357.0,34.11,218.0,18.56,315.0,15.99,214.0,14.11,94.0,17.19,16.0,17.93,355.0,15.96,353.0,21.71,95.0,25.38,4.0,18.97,38.0,50.540216,201.0,33.077905,211.0,63.461538,359.0,8.028546,251.0,54.772525,320.0,36.263736,323.0,69.983949,63.0,12.364946,347.0,48.452970,14.0,36.234357,92.0,62.941176,6.0,48.639053,97.0,0.086818,265.0,0.104566,257.0,NaN,10.264712,357.0,7.003028,242.0,18.314834,221.0,42.482341,349.0,39.202825,18.0,18.498091,216.0,52.100127,82.0,29.401782,271.0,64.6651,334.0,64.3683,324.0,95.3082,347.0,98.9012,312.0,113.105,335.0,111.4670,272.0,-12.56550,310.0,NaN,64.6651,335.0,64.6373,325.0,95.3082,347.0,98.9098,312.0,113.105,335.0,111.6740,272.0,-12.76410,310.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MWC,Mountain West Conference (MW),Air Force
3,2025,Akron,54.940898,34.0,16.354727,131.0,32.179054,108.0,26.950355,332.0,50.073783,134.0,17.270259,167.0,29.474548,161.0,33.054599,184.0,MAC,71.7,15.0,72.5,10.0,113.6,71.0,114.9,29.0,107.1,182.0,105.1,154.0,15.8,21.0,17.1,62.0,75.06,361.0,-1.94,351.0,-3.52,364.0,-2.16,359.0,-1.36,327.0,-1.75,324.0,-2.73,364.0,1.39962,245.0,38.91,30.0,19.00,192.0,17.71,257.0,21.16,130.0,17.74,287.0,24.35,69.0,48.76,16.0,18.17,321.0,14.88,235.0,11.53,159.0,6.57,255.0,33.22,18.0,19.19,299.0,20.43,135.0,15.44,214.0,11.65,312.0,55.220017,41.0,36.401674,50.0,75.087719,76.0,9.754163,144.0,50.991277,180.0,32.383420,92.0,72.321429,197.0,7.506471,32.0,45.200946,54.0,37.973438,146.0,57.894737,50.0,45.128779,29.0,0.102789,126.0,0.097795,196.0,NaN,6.575183,77.0,6.991334,244.0,15.552326,338.0,46.511628,276.0,37.936047,43.0,19.270420,157.0,50.991277,119.0,29.738303,253.0,72.4588,15.0,71.3708,16.0,115.7540,22.0,113.6890,66.0,104.558,145.0,107.1090,183.0,6.57907,99.0,13.0,72.5396,10.0,71.6561,15.0,114.8680,29.0,113.5550,71.0,105.141,154.0,107.0810,182.0,6.47358,100.0,13.0,East,March Madness,1.0,NaN,NaN,NaN,NaN,NaN,MAC,Mid-American Conference (MAC),Akron
4,2025,Alabama,56.600590,10.0,16.559930,142.0,33.725202,64.0,39.308309,30.0,47.820055,49.0,13.488046,351.0,29.426752,159.0,33.174792,187.0,SEC,75.3,1.0,76.1,1.0,126.8,4.0,118.4,9.0,96.5,28.0,106.2,175.0,14.9,4.0,16.7,15.0,78.07,61.0,1.61,33.0,3.10,2.0,0.21,149.0,-0.47,254.0,-0.12,206.0,2.35,5.0,2.98697,9.0,38.57,33.0,15.78,301.0,19.15,199.0,18.97,205.0,20.78,167.0,25.32,50.0,29.10,301.0,29.93,102.0,26.62,29.0,9.42,230.0,4.92,328.0,26.91,148.0,29.47,25.0,20.19,149.0,12.26,329.0,11.16,327.0,59.747435,4.0,35.326087,93.0,71.995708,192.0,10.121212,127.0,49.030303,98.0,30.355097,19.0,70.967742,118.0,12.075770,343.0,46.562632,35.0,34.601665,44.0,55.448997,91.0,44.692737,24.0,0.080505,317.0,0.101690,233.0,NaN,6.390933,56.0,5.437589,362.0,20.000000,121.0,45.126677,313.0,34.873323,86.0,19.753908,135.0,53.807782,36.0,26.438311,340.0,76.2512,1.0,74.8553,1.0,118.7250,9.0,126.5110,4.0,106.121,176.0,96.5798,32.0,29.93170,6.0,2.0,76.0703,1.0,75.2702,1.0,118.4340,9.0,126.8140,4.0,106.226,175.0,96.4694,28.0,30.34500,6.0,2.0,East,March Madness,1.0,No,NaN,NaN,NaN,Yes,SEC,Southeastern Conference (SEC),Alabama

In [10]:
# Check for missing data
print("Missing data in KenPom and Reference Data:")
print(full_kenpom_df.isnull().sum())

Missing data in KenPom and Reference Data:
Season                                            0
TeamName                                          0
eFGPct_off                                      855
RankeFGPct_off                                  855
TOPct_off                                       855
RankTOPct_off                                   855
ORPct_off                                       855
RankORPct_off                                   855
FTRate_off                                      855
RankFTRate_off                                  855
eFGPct_def                                      855
RankeFGPct_def                                  855
TOPct_def                                       855
RankTOPct_def                                   855
ORPct_def                                       855
RankORPct_def                                   855
FTRate_def                                      855
RankFTRate_def                                  855
Conference_extra                                855
Adjusted Temo_extra                             855
Adjusted Tempo Rank_extra                       855
Raw Tempo_extra                                 855
Raw Tempo Rank_extra                            855
Adjusted Offensive Efficiency_extra             855
Adjusted Offensive Efficiency Rank_extra        855
Raw Offensive Efficiency_extra                  855
Raw Offensive Efficiency Rank_extra             855
Adjusted Defensive Efficiency_extra             855
Adjusted Defensive Efficiency Rank_extra        855
Raw Defensive Efficiency_extra                  855
Raw Defensive Efficiency Rank_extra             855
Avg Possession Length (Offense)_extra          6796
Avg Possession Length (Offense) Rank_extra     6796
Avg Possession Length (Defense)_extra          6796
Avg Possession Length (Defense) Rank_extra     6796
AvgHeight_extra                                5098
RankAvgHeight_extra                            5098
CenterHeight_extra                             5098
RankCenterHeight_extra                         5098
PFHeight_extra                                 5098
RankPFHeight_extra                             5098
SFHeight_extra                                 5098
RankSFHeight_extra                             5098
SGHeight_extra                                 5098
RankSGHeight_extra                             5098
PGHeight_extra                                 5098
RankPGHeight_extra                             5098
EffectiveHeight_extra                          5098
RankEffectiveHeight_extra                      5098
Experience_extra                               5098
RankExperience_extra                           5098
Bench_extra                                    5098
BenchRank_extra                                5098
CenterPts_extra                                5098
RankCenterPts_extra                            5098
PFPts_extra                                    5098
RankPFPts_extra                                5098
SFPts_extra                                    5098
RankSFPts_extra                                5098
SGPts_extra                                    5098
RankSGPts_extra                                5098
PGPts_extra                                    5098
RankPGPts_extra                                5098
CenterOR_extra                                 5098
RankCenterOR_extra                             5098
PFOR_extra                                     5098
RankPFOR_extra                                 5098
SFOR_extra                                     5098
RankSFOR_extra                                 5098
SGOR_extra                                     5098
RankSGOR_extra                                 5098
PGOR_extra                                     5098
RankPGOR_extra                                 5098
CenterDR_extra                                 5098
RankCenterDR_extra                             5098
PFDR_extra                                     5098
RankPFDR_extra                                 5098
SFDR_extra                                     5098
RankSFDR_extra                                 5098
SGDR_extra                                     5098
RankSGDR_extra                                 5098
PGDR_extra                                     5098
RankPGDR_extra                                 5098
FG2Pct_extra                                   2403
RankFG2Pct_extra                               2403
FG3Pct_extra                                   2403
RankFG3Pct_extra                               2403
FTPct_extra                                    2403
RankFTPct_extra                                2403
BlockPct_extra                                 2403
RankBlockPct_extra                             2403
OppFG2Pct_extra                                2403
RankOppFG2Pct_extra                            2403
OppFG3Pct_extra                                2403
RankOppFG3Pct_extra                            2403
OppFTPct_extra                                 2403
RankOppFTPct_extra                             2403
OppBlockPct_extra                              2403
RankOppBlockPct_extra                          2403
FG3Rate_extra                                  2403
RankFG3Rate_extra                              2403
OppFG3Rate_extra                               2403
RankOppFG3Rate_extra                           2403
ARate_extra                                    2403
RankARate_extra                                2403
OppARate_extra                                 2403
RankOppARate_extra                             2403
StlRate_extra                                  2403
RankStlRate_extra                              2403
OppStlRate_extra                               2403
RankOppStlRate_extra                           2403
DFP_extra                                     14442
NSTRate_extra                                 12645
RankNSTRate_extra                             12645
OppNSTRate_extra                              12645
RankOppNSTRate_extra                          12645
OffFT_extra                                     983
RankOffFT_extra                                 983
Off2PtFG_extra                                  983
RankOff2PtFG_extra                              983
Off3PtFG_extra                                  983
RankOff3PtFG_extra                              983
DefFT_extra                                     983
RankDefFT_extra                                 983
Def2PtFG_extra                                  983
RankDef2PtFG_extra                              983
Def3PtFG_extra                                  983
RankDef3PtFG_extra                              983
Tempo_extra_x                                  2470
RankTempo_extra_x                              2470
AdjTempo_extra_x                               2470
RankAdjTempo_extra_x                           2470
OE_extra_x                                     2470
RankOE_extra_x                                 2470
AdjOE_extra_x                                  2470
RankAdjOE_extra_x                              2470
DE_extra_x                                     2470
RankDE_extra_x                                 2470
AdjDE_extra_x                                  2470
RankAdjDE_extra_x                              2470
AdjEM_extra_x                                  2470
RankAdjEM_extra_x                              2470
Seed_extra                                    13557
Tempo_extra_y                                   855
RankTempo_extra_y                               855
AdjTempo_extra_y                                855
RankAdjTempo_extra_y                            855
OE_extra_y                                      855
RankOE_extra_y                                  855
AdjOE_extra_y                                   855
RankAdjOE_extra_y                               855
DE_extra_y                                      855
RankDE_extra_y                                  855
AdjDE_extra_y                                   855
RankAdjDE_extra_y                               855
AdjEM_extra_y                                   855
RankAdjEM_extra_y                               855
Seed_ref                                      11785
Region_ref                                    11785
Post-Season Tournament_ref                    11785
Post-Season Tournament Sorting Index_ref      11785
Vulnerable Top 2 Seed?_ref                    15943
Tournament Winner?_ref                        16178
Tournament Championship?_ref                  16149
Final Four?_ref                               16075
Top 12 in AP Top 25 During Week 6?_ref        15782
Conference                                      818
Mapped Conference Name                          818
Mapped ESPN Team Name                           818
dtype: int64

In [11]:
# Show missing 'eFGPct_off' values
#missing_efg = full_kenpom_df[full_kenpom_df['eFGPct_off'].isnull()]
#print("\nRows with missing 'eFGPct_off':")
#print(missing_efg)

In [12]:
# Print shape of full_kenpom_df
full_kenpom_df.shape

(16205, 169)

In [13]:
# Explore missing data in full_kenpom_df
missing_data = full_kenpom_df.isnull().sum()
missing_data = missing_data[missing_data > 0].sort_values(ascending=False)
print("Columns with missing data in KenPom and Reference Data:")
print(missing_data)

Columns with missing data in KenPom and Reference Data:
Tournament Winner?_ref                        16178
Tournament Championship?_ref                  16149
Final Four?_ref                               16075
Vulnerable Top 2 Seed?_ref                    15943
Top 12 in AP Top 25 During Week 6?_ref        15782
DFP_extra                                     14442
Seed_extra                                    13557
RankNSTRate_extra                             12645
NSTRate_extra                                 12645
OppNSTRate_extra                              12645
RankOppNSTRate_extra                          12645
Seed_ref                                      11785
Region_ref                                    11785
Post-Season Tournament Sorting Index_ref      11785
Post-Season Tournament_ref                    11785
Avg Possession Length (Offense) Rank_extra     6796
Avg Possession Length (Offense)_extra          6796
Avg Possession Length (Defense)_extra          6796
Avg Possession Length (Defense) Rank_extra     6796
SGPts_extra                                    5098
RankSFPts_extra                                5098
RankPFPts_extra                                5098
PFPts_extra                                    5098
RankSGPts_extra                                5098
PGPts_extra                                    5098
RankCenterPts_extra                            5098
RankPGPts_extra                                5098
CenterOR_extra                                 5098
RankCenterOR_extra                             5098
CenterPts_extra                                5098
BenchRank_extra                                5098
SFPts_extra                                    5098
SGOR_extra                                     5098
PFOR_extra                                     5098
RankPFOR_extra                                 5098
SFOR_extra                                     5098
RankSFOR_extra                                 5098
RankExperience_extra                           5098
SGDR_extra                                     5098
RankSGOR_extra                                 5098
PGOR_extra                                     5098
RankPGOR_extra                                 5098
CenterDR_extra                                 5098
RankCenterDR_extra                             5098
PFDR_extra                                     5098
RankPFDR_extra                                 5098
Bench_extra                                    5098
RankPFHeight_extra                             5098
Experience_extra                               5098
PFHeight_extra                                 5098
RankPGDR_extra                                 5098
PGDR_extra                                     5098
RankSGDR_extra                                 5098
RankEffectiveHeight_extra                      5098
RankAvgHeight_extra                            5098
CenterHeight_extra                             5098
RankCenterHeight_extra                         5098
AvgHeight_extra                                5098
RankSFDR_extra                                 5098
PGHeight_extra                                 5098
SFHeight_extra                                 5098
EffectiveHeight_extra                          5098
RankPGHeight_extra                             5098
SFDR_extra                                     5098
RankSGHeight_extra                             5098
SGHeight_extra                                 5098
RankSFHeight_extra                             5098
AdjDE_extra_x                                  2470
RankTempo_extra_x                              2470
AdjTempo_extra_x                               2470
RankAdjTempo_extra_x                           2470
OE_extra_x                                     2470
RankOE_extra_x                                 2470
AdjOE_extra_x                                  2470
RankAdjOE_extra_x                              2470
Tempo_extra_x                                  2470
DE_extra_x                                     2470
RankDE_extra_x                                 2470
AdjEM_extra_x                                  2470
RankAdjEM_extra_x                              2470
RankAdjDE_extra_x                              2470
RankARate_extra                                2403
FG3Rate_extra                                  2403
RankFG3Rate_extra                              2403
OppFG3Rate_extra                               2403
RankOppFG3Rate_extra                           2403
ARate_extra                                    2403
RankOppARate_extra                             2403
OppARate_extra                                 2403
OppBlockPct_extra                              2403
StlRate_extra                                  2403
OppStlRate_extra                               2403
RankOppStlRate_extra                           2403
RankOppBlockPct_extra                          2403
RankStlRate_extra                              2403
RankOppFTPct_extra                             2403
RankFTPct_extra                                2403
OppFTPct_extra                                 2403
FG2Pct_extra                                   2403
RankFG2Pct_extra                               2403
RankFG3Pct_extra                               2403
FTPct_extra                                    2403
FG3Pct_extra                                   2403
BlockPct_extra                                 2403
OppFG2Pct_extra                                2403
RankOppFG2Pct_extra                            2403
OppFG3Pct_extra                                2403
RankBlockPct_extra                             2403
RankOppFG3Pct_extra                            2403
RankOff2PtFG_extra                              983
RankDef3PtFG_extra                              983
Def3PtFG_extra                                  983
RankDef2PtFG_extra                              983
Def2PtFG_extra                                  983
RankDefFT_extra                                 983
DefFT_extra                                     983
Off3PtFG_extra                                  983
RankOff3PtFG_extra                              983
Off2PtFG_extra                                  983
OffFT_extra                                     983
RankOffFT_extra                                 983
OE_extra_y                                      855
RankAdjTempo_extra_y                            855
AdjTempo_extra_y                                855
RankTempo_extra_y                               855
Tempo_extra_y                                   855
RankOE_extra_y                                  855
RankAdjOE_extra_y                               855
DE_extra_y                                      855
RankDE_extra_y                                  855
AdjDE_extra_y                                   855
RankAdjDE_extra_y                               855
AdjEM_extra_y                                   855
RankAdjEM_extra_y                               855
AdjOE_extra_y                                   855
eFGPct_off                                      855
RankeFGPct_off                                  855
Raw Defensive Efficiency Rank_extra             855
TOPct_off                                       855
RankTOPct_off                                   855
ORPct_off                                       855
RankORPct_off                                   855
FTRate_off                                      855
RankFTRate_off                                  855
eFGPct_def                                      855
RankeFGPct_def                                  855
TOPct_def                                       855
RankTOPct_def                                   855
ORPct_def                                       855
RankORPct_def                                   855
FTRate_def                                      855
RankFTRate_def                                  855
Conference_extra                                855
Adjusted Temo_extra                             855
Adjusted Tempo Rank_extra                       855
Raw Tempo_extra                                 855
Raw Tempo Rank_extra                            855
Adjusted Offensive Efficiency_extra             855
Adjusted Offensive Efficiency Rank_extra        855
Raw Offensive Efficiency_extra                  855
Raw Offensive Efficiency Rank_extra             855
Adjusted Defensive Efficiency_extra             855
Adjusted Defensive Efficiency Rank_extra        855
Raw Defensive Efficiency_extra                  855
Conference                                      818
Mapped Conference Name                          818
Mapped ESPN Team Name                           818
dtype: int64

# Addressing missing values and unneccessary data

## Remove duplicate columns

In [14]:
# Identify duplicate base column names
cols = full_kenpom_df.columns
base_names = {}

for col in cols:
    if col.endswith('_x') or col.endswith('_y'):
        base = col[:-2]
        base_names.setdefault(base, []).append(col)

# Compare missing counts and drop worse version
for base, variants in base_names.items():
    if len(variants) == 2:
        col1, col2 = variants
        if full_kenpom_df[col1].isna().sum() <= full_kenpom_df[col2].isna().sum():
            full_kenpom_df.drop(columns=col2, inplace=True)
            full_kenpom_df.rename(columns={col1: base}, inplace=True)
        else:
            full_kenpom_df.drop(columns=col1, inplace=True)
            full_kenpom_df.rename(columns={col2: base}, inplace=True)

## Drop rank columns and not needed columns

In [15]:
# Drop rank columns
rank_cols = [col for col in full_kenpom_df.columns if 'Rank' in col]
full_kenpom_df.drop(columns=rank_cols, inplace=True)

In [16]:
# Unnec columns
Unnec_columns = leakage_cols = [
    'Vulnerable Top 2 Seed?_ref',
    'Seed_ref',
    'Region_ref',
    'Post-Season Tournament Sorting Index_ref',
    'Mapped Conference Name',
    'Mapped ESPN Team Name'
]

full_kenpom_df.drop(columns=[col for col in leakage_cols if col in full_kenpom_df.columns], inplace=True)

## Impute median for remaining statistical values

In [17]:
numeric_cols = full_kenpom_df.select_dtypes(include=[np.number]).columns

for col in numeric_cols:
    if full_kenpom_df[col].isna().sum() > 0:
        full_kenpom_df[col].fillna(full_kenpom_df[col].median(), inplace=True)

In [18]:
# Check changes

# Explore missing data in full_kenpom_df
missing_data = full_kenpom_df.isnull().sum()
missing_data = missing_data[missing_data > 0].sort_values(ascending=False)
print("Columns with missing data in KenPom and Reference Data:")
print(missing_data)

Columns with missing data in KenPom and Reference Data:
Tournament Winner?_ref                    16178
Tournament Championship?_ref              16149
Final Four?_ref                           16075
Top 12 in AP Top 25 During Week 6?_ref    15782
Post-Season Tournament_ref                11785
Conference_extra                            855
Conference                                  818
dtype: int64

# Part 2 team_master data

In [19]:
team_master.head()

,YEAR,TEAM NO,TEAM,SEED,ROUND,O RATE,D RATE,RELATIVE RATING,OPPONENT ADJUST,PACE ADJUST,O RATE RANK,D RATE RANK,TRUE TEMPO,TRUE TEMPO RANK,HOME RANK,KILL SHOTS PER GAME,KILL SHOTS CONCEDED PER GAME,TOTAL KILL SHOTS,TOTAL KILL SHOTS CONCEDED,RELATIVE RATING RANK,OPPONENT ADJUST RANK,PACE ADJUST RANK,KILL SHOTS PER GAME RANK,KILL SHOTS CONCEDED PER GAME RANK,TOTAL KILL SHOTS RANK,TOTAL KILL SHOTS CONCEDED RANK,YEAR_part2_x,TEAM_part2_x,SEED_part2_x,ROUND_part2_x,POWER RATING_part2,POWER RATING RANK_part2,YEAR_part2_y,TEAM_part2_y,SEED_part2_y,ROUND_part2_y,AP VOTES_part2_x,AP RANK_part2_x,RANK?_part2_x,YEAR_part2_x.1,TEAM ID_part2_x,TEAM_part2_x.1,SEED_part2_x.1,ROUND_part2_x.1,BADJ EM_part2_x,BADJ O_part2_x,BADJ D_part2_x,BARTHAG_part2_x,GAMES_part2_x,W_part2_x,L_part2_x,WIN%_part2_x,EFG%_part2_x,EFG%D_part2_x,FTR_part2_x,FTRD_part2_x,TOV%_part2_x,TOV%D_part2_x,OREB%_part2_x,DREB%_part2_x,OP OREB%_part2_x,OP DREB%_part2_x,RAW T_part2_x,2PT%_part2_x,2PT%D_part2_x,3PT%_part2_x,3PT%D_part2_x,BLK%_part2_x,BLKED%_part2_x,AST%_part2_x,OP AST%_part2_x,2PTR_part2_x,3PTR_part2_x,2PTRD_part2_x,3PTRD_part2_x,BADJ T_part2_x,AVG HGT_part2_x,EFF HGT_part2_x,EXP_part2_x,TALENT_part2_x,FT%_part2_x,OP FT%_part2_x,PPPO_part2_x,PPPD_part2_x,ELITE SOS_part2_x,WAB_part2_x,BADJ EM RANK_part2_x,BADJ O RANK_part2_x,BADJ D RANK_part2_x,BARTHAG RANK_part2_x,EFG% RANK_part2_x,EFGD% RANK_part2_x,FTR RANK_part2_x,FTRD RANK_part2_x,TOV% RANK_part2_x,TOV%D RANK_part2_x,OREB% RANK_part2_x,DREB% RANK_part2_x,OP OREB% RANK_part2_x,OP DREB% RANK_part2_x,RAW T RANK_part2_x,2PT% RANK_part2_x,2PT%D RANK_part2_x,3PT% RANK_part2_x,3PT%D RANK_part2_x,BLK% RANK_part2_x,BLKED% RANK_part2_x,AST% RANK_part2_x,OP AST% RANK_part2_x,2PTR RANK_part2_x,3PTR RANK_part2_x,2PTRD RANK_part2_x,3PTRD RANK_part2_x,BADJT RANK_part2_x,AVG HGT RANK_part2_x,EFF HGT RANK_part2_x,EXP RANK_part2_x,TALENT RANK_part2_x,FT% RANK_part2_x,OP FT% RANK_part2_x,PPPO RANK_part2_x,PPPD RANK_part2_x,ELITE SOS RANK_part2_x,YEAR_part2_y.1,TEAM ID_part2_y,TEAM_part2_y.1,SEED_part2_y.1,ROUND_part2_y.1,BADJ EM_part2_y,BADJ O_part2_y,BADJ D_part2_y,BARTHAG_part2_y,GAMES_part2_y,W_part2_y,L_part2_y,WIN%_part2_y,EFG%_part2_y,EFG%D_part2_y,FTR_part2_y,FTRD_part2_y,TOV%_part2_y,TOV%D_part2_y,OREB%_part2_y,DREB%_part2_y,OP OREB%_part2_y,OP DREB%_part2_y,RAW T_part2_y,2PT%_part2_y,2PT%D_part2_y,3PT%_part2_y,3PT%D_part2_y,BLK%_part2_y,BLKED%_part2_y,AST%_part2_y,OP AST%_part2_y,2PTR_part2_y,3PTR_part2_y,2PTRD_part2_y,3PTRD_part2_y,BADJ T_part2_y,AVG HGT_part2_y,EFF HGT_part2_y,EXP_part2_y,TALENT_part2_y,FT%_part2_y,OP FT%_part2_y,PPPO_part2_y,PPPD_part2_y,ELITE SOS_part2_y,WAB_part2_y,BADJ EM RANK_part2_y,BADJ O RANK_part2_y,BADJ D RANK_part2_y,BARTHAG RANK_part2_y,EFG% RANK_part2_y,EFGD% RANK_part2_y,FTR RANK_part2_y,FTRD RANK_part2_y,TOV% RANK_part2_y,TOV%D RANK_part2_y,OREB% RANK_part2_y,DREB% RANK_part2_y,OP OREB% RANK_part2_y,OP DREB% RANK_part2_y,RAW T RANK_part2_y,2PT% RANK_part2_y,2PT%D RANK_part2_y,3PT% RANK_part2_y,3PT%D RANK_part2_y,BLK% RANK_part2_y,BLKED% RANK_part2_y,AST% RANK_part2_y,OP AST% RANK_part2_y,2PTR RANK_part2_y,3PTR RANK_part2_y,2PTRD RANK_part2_y,3PTRD RANK_part2_y,BADJT RANK_part2_y,AVG HGT RANK_part2_y,EFF HGT RANK_part2_y,EXP RANK_part2_y,TALENT RANK_part2_y,FT% RANK_part2_y,OP FT% RANK_part2_y,PPPO RANK_part2_y,PPPD RANK_part2_y,ELITE SOS RANK_part2_y,YEAR_part2_x.2,TEAM ID_part2_x.1,TEAM_part2_x.2,SEED_part2_x.2,ROUND_part2_x.2,BADJ EM_part2_x.1,BADJ O_part2_x.1,BADJ D_part2_x.1,BARTHAG_part2_x.1,GAMES_part2_x.1,W_part2_x.1,L_part2_x.1,WIN%_part2_x.1,EFG%_part2_x.1,EFG%D_part2_x.1,FTR_part2_x.1,FTRD_part2_x.1,TOV%_part2_x.1,TOV%D_part2_x.1,OREB%_part2_x.1,DREB%_part2_x.1,OP OREB%_part2_x.1,OP DREB%_part2_x.1,RAW T_part2_x.1,2PT%_part2_x.1,2PT%D_part2_x.1,3PT%_part2_x.1,3PT%D_part2_x.1,BLK%_part2_x.1,BLKED%_part2_x.1,AST%_part2_x.1,OP AST%_part2_x.1,2PTR_part2_x.1,3PTR_part2_x.1,2PTRD_part2_x.1,3PTRD_part2_x.1,BADJ T_part2_x.1,AVG HGT_part2_x.1,EFF HGT_part2_x.1,EXP_part2_x.1,TALENT_part2_x.1,FT%_part2_x.1,OP FT%_part2_x.1,PPPO_part2_x.1,PPPD_part2_x.1,ELITE SOS_part2_x.1,WAB_part2_x.1,BADJ EM RANK_part2_x.1,BADJ O RANK_part2_x.1,BADJ D RANK_part2_x.1,BARTHAG RANK_part2_x.1,EFG% RANK_part2_x.1,EFGD% RANK_part2_x.1,FTR RANK_part2_x.1,FTRD RANK_part2_x.1,TOV% RANK_part2_x.1,TOV%D RANK_part2_x.1,OREB% RANK_part2_x.1,DREB% RANK_part2_x.1,OP OREB% RANK_part2_x.1,OP DREB% RANK_part2_x.1,RAW T RANK_part2_x.1,2PT% RANK_part2_x.1,2PT%D RANK_part2_x.1,3PT% RANK_part2_x.1,3PT%D RANK_part2_x.1,BLK% RANK_part2_x.1,BLKED% RANK_part2_x.1,AST% RANK_part2_x.1,OP AST% RANK_part2_x.1,2PTR RANK_part2_x.1,3PTR RANK_part2_x.1,2PTRD RANK_part2_x.1,3PTRD RANK_part2_x.1,BADJT RANK_part2_x.1,AVG HGT RANK_part2_x.1,EFF HGT RANK_part2_x.1,EXP RANK_part2_x.1,TALENT RANK_part2_x.1,FT% RANK_part2_x.1,OP FT% RANK_part2_x.1,PPPO RANK_part2_x.1,PPPD RANK_part2_x.1,ELITE SOS RANK_part2_x.1,YEAR_part2_y.2,TEAM ID_part2_y.1,TEAM_part2_y.2,SEED_part2_y.2,ROUND_part2_y.2,BADJ EM_part2_y.1,BADJ O_part2_y.1,BADJ D_part2_y.1,BARTHAG_part2_y.1,GAMES_part2_y.1,W_part2_y.1,L_part2_y.1,WIN%_part2_y.1,EFG%_part2_y.1,EFG%D_part2_y.1,FTR_part2_y.1,FTRD_part2_y.1,TOV%_part2_y.1,TOV%D_part2_y.1,OREB%_part2_y.1,DREB%_part2_y.1,OP OREB%_part2_y.1,OP DREB%_part2_y.1,RAW T_part2_y.1,2PT%_part2_y.1,2PT%D_part2_y.1,3PT%_part2_y.1,3PT%D_part2_y.1,BLK%_part2_y.1,BLKED%_part2_y.1,AST%_part2_y.1,OP AST%_part2_y.1,2PTR_part2_y.1,3PTR_part2_y.1,2PTRD_part2_y.1,3PTRD_part2_y.1,BADJ T_part2_y.1,AVG HGT_part2_y.1,EFF HGT_part2_y.1,EXP_part2_y.1,TALENT_part2_y.1,FT%_part2_y.1,OP FT%_part2_y.1,PPPO_part2_y.1,PPPD_part2_y.1,ELITE SOS_part2_y.1,WAB_part2_y.1,BADJ EM RANK_part2_y.1,BADJ O RANK_part2_y.1,BADJ D RANK_part2_y.1,BARTHAG RANK_part2_y.1,EFG% RANK_part2_y.1,EFGD% RANK_part2_y.1,FTR RANK_part2_y.1,FTRD RANK_part2_y.1,TOV% RANK_part2_y.1,TOV%D RANK_part2_y.1,OREB% RANK_part2_y.1,DREB% RANK_part2_y.1,OP OREB% RANK_part2_y.1,OP DREB% RANK_part2_y.1,RAW T RANK_part2_y.1,2PT% RANK_part2_y.1,2PT%D RANK_part2_y.1,3PT% RANK_part2_y.1,3PT%D RANK_part2_y.1,BLK% RANK_part2_y.1,BLKED% RANK_part2_y.1,AST% RANK_part2_y.1,OP AST% RANK_part2_y.1,2PTR RANK_part2_y.1,3PTR RANK_part2_y.1,2PTRD RANK_part2_y.1,3PTRD RANK_part2_y.1,BADJT RANK_part2_y.1,AVG HGT RANK_part2_y.1,EFF HGT RANK_part2_y.1,EXP RANK_part2_y.1,TALENT RANK_part2_y.1,FT% RANK_part2_y.1,OP FT% RANK_part2_y.1,PPPO RANK_part2_y.1,PPPD RANK_part2_y.1,ELITE SOS RANK_part2_y.1,YEAR_part2_x.3,TEAM_part2_x.3,SEED_part2_x.3,ROUND_part2_x.3,EASY DRAW_part2,TOUGH DRAW_part2,DARK HORSE_part2,UPSET ALERT_part2,CINDERELLA_part2,YEAR_part2_y.3,TEAM_part2_y.3,SEED_part2_y.3,ROUND_part2_y.3,POWER_part2,PATH_part2,DRAW_part2,WINS_part2,POOL VALUE_part2,POOL S-RANK_part2,NCAA S-RANK_part2,VAL Z-SCORE_part2,POWER-PATH_part2,YEAR_part2_x.4,CONF_part2_x,CONF ID_part2,QUAD NO_part2,QUAD ID_part2,TEAM ID_part2_x.2,TEAM_part2_x.4,SEED_part2_x.4,ROUND_part2_x.4,K TEMPO_part2,K TEMPO RANK_part2,KADJ T_part2,KADJ T RANK_part2,K OFF_part2,KO RANK_part2,KADJ O_part2,KADJ O RANK_part2,K DEF_part2,KD RANK_part2,KADJ D_part2,KADJ D RANK_part2,KADJ EM_part2,KADJ EM RANK_part2,BADJ EM_part2,BADJ O_part2,BADJ D_part2,BARTHAG_part2,GAMES_part2,W_part2,L_part2,WIN%_part2,EFG%_part2,EFG%D_part2,FTR_part2,FTRD_part2,TOV%_part2,TOV%D_part2,OREB%_part2,DREB%_part2,OP OREB%_part2,OP DREB%_part2,RAW T_part2,2PT%_part2,2PT%D_part2,3PT%_part2,3PT%D_part2,BLK%_part2,BLKED%_part2,AST%_part2,OP AST%_part2,2PTR_part2,3PTR_part2,2PTRD_part2,3PTRD_part2,BADJ T_part2,AVG HGT_part2,EFF HGT_part2,EXP_part2,TALENT_part2,FT%_part2,OP FT%_part2,PPPO_part2,PPPD_part2,ELITE SOS_part2,WAB_part2,BADJ EM RANK_part2,BADJ O RANK_part2,BADJ D RANK_part2,BARTHAG RANK_part2,EFG% RANK_part2,EFGD% RANK_part2,FTR RANK_part2,FTRD RANK_part2,TOV% RANK_part2,TOV%D RANK_part2,OREB% RANK_part2,DREB% RANK_part2,OP OREB% RANK_part2,OP DREB% RANK_part2,RAW T RANK_part2,2PT% RANK_part2,2PT%D RANK_part2,3PT% RANK_part2,3PT%D RANK_part2,BLK% RANK_part2,BLKED% RANK_part2,AST% RANK_part2,OP AST% RANK_part2,2PTR RANK_part2,3PTR RANK_part2,2PTRD RANK_part2,3PTRD RANK_part2,BADJT RANK_part2,AVG HGT RANK_part2,EFF HGT RANK_part2,EXP RANK_part2,TALENT RANK_part2,FT% RANK_part2,OP FT% RANK_part2,PPPO RANK_part2,PPPD RANK_part2,ELITE SOS RANK_part2,YEAR_part2_y.4,TEAM_part2_y.4,SEED_part2_y.4,ROUND_part2_y.4,PRESEASON KADJ EM RANK_part2,PRESEASON KADJ EM_part2,PRESEASON KADJ O_part2,PRESEASON KADJ O RANK_part2,PRESEASON KADJ D_part2,PRESEASON KADJ D RANK_part2,PRESEASON KADJ T_part2,PRESEASON KADJ T RANK_part2,KADJ EM RANK CHANGE_part2,KADJ EM CHANGE_part2,KADJ T RANK CHANGE_part2,YEAR_part2_x.5,TEAM_part2_x.5,SEED_part2_x.5,ROUND_part2_x.5,AP VOTES_part2_y,AP RANK_part2_y,RANK?_part2_y,YEAR_part2_y.5,TEAM_part2_y.5,R64_part2,R32_part2,S16_part2,E8_part2,F4_part2,FINALS_part2,YEAR_part2_x.6,TEAM_part2_x.6,SEED_part2_y.5,ROUND_part2_y.5,NET RPI_part2,RESUME_part2,WAB RANK_part2,ELO_part2,B POWER_part2,Q1 W_part2,Q2 W_part2,Q1 PLUS Q2 W_part2,Q3 Q4 L_part2,PLUS 500_part2,R SCORE_part2,BID TYPE_part2,YEAR_part2_y.6,TEAM ID_part2_y.2,TEAM_part2_y.6,CONF_part2_y,DUNKS FG%_part2,DUNKS SHARE_part2,DUNKS FG%D_part2,DUNKS D SHARE_part2,CLOSE TWOS FG%_part2,CLOSE TWOS SHARE_part2,CLOSE TWOS FG%D_part2,CLOSE TWOS D SHARE_part2,FARTHER TWOS FG%_part2,FARTHER TWOS SHARE_part2,FARTHER TWOS FG%D_part2,FARTHER TWOS D SHARE_part2,THREES FG%_part2,THREES SHARE_part2,THREES FG%D_part2,THREES D SHARE_part2,DUNKS FG% RANK_part2,DUNKS SHARE RANK_part2,DUNKS FG%D RANK_part2,DUNKS D SHARE RANK_part2,CLOSE TWOS FG% RANK_part2,CLOSE TWOS SHARE RANK_part2,CLOSE TWOS FG%D RANK_part2,CLOSE TWOS D SHARE RANK_part2,FARTHER TWOS FG% RANK_part2,FARTHER TWOS SHARE RANK_part2,FARTHER TWOS FG%D RANK_part2,FARTHER TWOS D SHARE RANK_part2,THREES FG% RANK_part2,THREES SHARE RANK_part2,THREES FG%D RANK_part2,THREES D SHARE RANK_part2,YEAR_part2_x.7,TEAM_part2_x.7,SEED_part2_x.6,ROUND_part2_x.6,TR RANK_part2_x,TR RATING_part2_x,V 1-25 WINS_part2_x,V 1-25 LOSS_part2_x,V 26-50 WINS_part2_x,V 26-50 LOSS_part2_x,V 51-100 WINS_part2_x,V 51-100 LOSS_part2_x,HI_part2_x,LO_part2_x,LAST_part2_x,YEAR_part2_y.7,TEAM_part2_y.7,SEED_part2_y.6,ROUND_part2_y.6,TR RANK_part2_y,TR RATING_part2_y,V 1-25 WINS_part2_y,V 1-25 LOSS_part2_y,V 26-50 WINS_part2_y,V 26-50 LOSS_part2_y,V 51-100 WINS_part2_y,V 51-100 LOSS_part2_y,HI_part2_y,LO_part2_y,LAST_part2_y,YEAR_part2_x.8,TEAM_part2_x.8,SEED_part2_x.7,ROUND_part2_x.7,TR RANK_part2_x.1,TR RATING_part2_x.1,V 1-25 WINS_part2_x.1,V 1-25 LOSS_part2_x.1,V 26-50 WINS_part2_x.1,V 26-50 LOSS_part2_x.1,V 51-100 WINS_part2_x.1,V 51-100 LOSS_part2_x.1,HI_part2_x.1,LO_part2_x.1,LAST_part2_x.1,YEAR_part2_y.8,TEAM_part2_y.8,SEED_part2_y.7,ROUND_part2_y.7,TR RANK_part2_y.1,TR RATING_part2_y.1,V 1-25 WINS_part2_y.1,V 1-25 LOSS_part2_y.1,V 26-50 WINS_part2_y.1,V 26-50 LOSS_part2_y.1,V 51-100 WINS_part2_y.1,V 51-100 LOSS_part2_y.1,HI_part2_y.1,LO_part2_y.1,LAST_part2_y.1,SOS RANK_part2,SOS RATING_part2,SOS HI_part2,SOS LO_part2,SOS LAST_part2,LUCK RANK_part2,LUCK RATING_part2,LUCK V 1-25 WINS_part2,LUCK V 1-25 LOSS_part2,LUCK V 26-50 WINS_part2,LUCK V 26-50 LOSS_part2,LUCK V 51-100 WINS_part2,LUCK V 51-100 LOSS_part2,LUCK HI_part2,LUCK LO_part2,LUCK LAST_part2,CONSISTENCY RANK_part2,CONSISTENCY TR RATING_part2,CONSISTENCY V 1-25 WINS_part2,CONSISTENCY V 1-25 LOSS_part2,CONSISTENCY V 26-50 WINS_part2,CONSISTENCY V 26-50 LOSS_part2,CONSISTENCY V 51-100 WINS_part2,CONSISTENCY V 51-100 LOSS_part2,CONSISTENCY HI_part2,CONSISTENCY LO_part2,CONSISTENCY LAST_part2,YEAR_part2_x.9,BY YEAR NO_part2_x,BY ROUND NO_part2_x,TEAM_part2_x.9,SEED_part2_x.8,ROUND_part2_x.8,COLLEGE CITY_part2,COLLEGE STATE_part2,COLLEGE LOCATION_part2,COLLEGE TIME ZONE_part2,COLLEGE TIME ZONE VALUE_part2,DAYLIGHT SAVINGS TIME_part2,COLLEGE LATITUDE_part2,COLLEGE LONGITUDE_part2,GAME CITY_part2,GAME STATE_part2,GAME LOCATION_part2,GAME TIME ZONE_part2,GAME TIME ZONE VALUE_part2,DAYLIGHT SAVINGS TIME.1_part2,GAME LATITUDE_part2,GAME LONGITUDE_part2,TIME ZONE COMBINATION_part2,DIRECTION_part2,LONGITUDE DIFF_part2,TIME ZONES CROSSED_part2,TIME ZONES CROSSED VALUE_part2,DISTANCE (KM)_part2,DISTANCE (MI)_part2,YEAR_part2_y.9,BY YEAR NO_part2_y,BY ROUND NO_part2_y,TEAM_part2_y.9,SEED_part2_y.8,ROUND_part2_y.8,CURRENT ROUND_part2_x,SCORE_part2,YEAR_part2_x.10,BY YEAR NO_part2,BY ROUND NO_part2,TEAM_part2_x.10,SEED_part2_x.9,ROUND_part2_x.9,CURRENT ROUND_part2_y,YEAR_part2_y.10,TEAM_part2_y.10,SEED_part2_y.9,ROUND_part2_y.9,Z RATING_part2,Z RATING RANK_part2
0,2025.0,1147.0,Akron,13.0,0.0,6.277529,0.567429,6.844958,4.509381,1.703296,74.0,154.0,72.497815,17.0,161.0,0.593750,0.437500,19.0,14.0,56.0,30.0,28.0,42.0,56.0,46.0,56.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025.0,2.0,Akron,13.0,0.0,4.7,108.6,103.9,0.625,18.0,12.0,6.0,66.666667,53.6,49.9,26.9,31.7,17.9,17.5,31.0,71.2,28.8,69.0,73.6,53.4,50.7,35.9,32.4,9.7,8.0,55.4,46.7,56.9,43.1,63.0,37.0,73.0,75.063,77.508,2.383,16.228,76.6,71.7,1.096,1.035,14.146,-2.7,110.0,124.0,121.0,110.0,38.0,92.0,305.0,111.0,191.0,117.0,126.0,91.0,91.0,126.0,6.0,56.0,125.0,62.0,87.0,116.0,38.0,54.0,30.0,282.0,86.0,255.0,112.0,10.0,361.0,364.0,73.0,149.0,48.0,143.0,55.0,54.0,307.0,2025.0,2.0,Akron,13.0,0.0,6.2,109.6,103.4,0.661,12.0,8.0,4.0,66.666667,54.3,48.8,25.8,31.7,18.3,15.4,30.8,73.1,26.9,69.2,74.0,54.6,50.8,35.9,30.3,9.6,9.1,57.1,48.5,57.7,42.3,61.9,38.1,73.7,75.063,77.508,2.383,16.228,78.2,70.6,1.096,1.032,16.284,-1.5,97.0,108.0,103.0,96.0,34.0,52.0,315.0,112.0,217.0,245.0,122.0,42.0,42.0,122.0,5.0,33.0,120.0,68.0,30.0,121.0,91.0,33.0,59.0,267.0,100.0,212.0,154.0,6.0,361.0,364.0,73.0,149.0,34.0,96.0,49.0,50.0,283.0,2025.0,2.0,Akron,13.0,0.0,9.1,119.1,110.0,0.714,14.0,14.0,0.0,100.0,57.8,49.0,26.7,36.4,14.8,16.7,36.2,70.8,29.2,63.8,70.8,59.3,50.5,37.4,31.2,9.9,5.5,62.2,42.1,51.7,48.3,60.6,39.4,70.6,75.063,77.508,2.383,16.228,72.7,74.4,1.235,1.058,4.119,0.8,95.0,29.0,249.0,101.0,26.0,168.0,339.0,305.0,80.0,254.0,45.0,211.0,211.0,45.0,54.0,20.0,228.0,68.0,96.0,181.0,21.0,53.0,54.0,344.0,22.0,148.0,219.0,60.0,361.0,364.0,73.0,149.0,181.0,278.0,10.0,252.0,241.0,2025.0,2.0,Akron,13.0,0.0,2.0,106.8,104.8,0.554,6.0,4.0,2.0,66.666667,52.1,52.4,29.1,31.5,17.2,22.0,31.4,66.7,33.3,68.6,72.8,50.7,50.4,35.9,37.4,9.9,5.7,51.8,42.9,55.4,44.6,65.4,34.6,71.6,75.063,77.508,2.383,16.228,73.9,74.1,1.096,1.041,9.868,-1.2,150.0,151.0,183.0,151.0,101.0,248.0,246.0,152.0,201.0,32.0,136.0,285.0,285.0,136.0,29.0,156.0,202.0,87.0,286.0,134.0,77.0,147.0,80.0,286.0,79.0,262.0,105.0,38.0,361.0,364.0,73.0,149.0,146.0,237.0,90.0,181.0,221.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025.0,Akron,13.0,0.0,57.5,80.8,NaN,0.0,2.0,54.0,53.0,NaN,-23.3,2025.0,MAC,17.0,66.0,2.0,2.0,Akron,13.0,0.0,72.4588,15.0,71.4456,16.0,115.754,21.0,113.749,66.0,104.558,145.0,107.1760,183.0,6.57261,99.0,6.861,113.691,106.830,0.672,32.0,26.0,6.0,81.25000,55.4,49.5,26.8,33.7,16.6,17.2,33.3,71.0,29.0,66.7,72.4,55.8,50.6,36.6,31.9,9.8,7.0,58.5,44.7,54.6,45.4,62.0,38.0,71.176,75.063,77.508,2.383,16.228,74.9,73.0,1.156,1.045,9.759,-1.8,99.0,62.0,186.0,101.0,33.0,114.0,334.0,203.0,148.0,177.0,78.0,142.0,142.0,78.0,15.0,35.0,171.0,52.0,75.0,144.0,16.0,46.0,26.0,314.0,52.0,216.0,152.0,19.0,361.0,364.0,73.0,149.0,86.0,239.0,25.0,145.0,305.0,2025.0,Akron,13.0,0.0,130.0,2.94,102.6,143.0,99.7,126.0,69.7,291.0,31.0,3.63,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025.0,Akron,11.13%,3.59%,0.50%,0.19%,0.09%,0.05%,2025.0,Akron,13.0,0.0,91.0,112.0,65.0,45.0,104.0,0.0,1.0,1.0,3.0,21.0,0.02,Auto,2025.0,2.0,Akron,MAC,85.9,7.0,80.0,3.7,61.8,38.2,55.3,41.7,42.0,16.5,41.0,20.3,36.6,45.4,31.9,38.0,55.0,40.0,7.0,5.0,42.0,34.0,24.0,66.0,22.0,56.0,61.0,8.0,20.0,14.0,28.0,26.0,2025.0,Akron,13.0,0.0,95.0,5.6,0.0,1.0,0.0,0.0,1.0,1.0,29.0,213.0,95.0,2025.0,Akron,13.0,0.0,99.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,89.0,295.0,99.0,2025.0,Akron,13.0,0.0,134.0,2.9,0.0,1.0,0.0,0.0,0.0,1.0,37.0,350.0,128.0,2025.0,Akron,13.0,0.0,106.0,4.4,0.0,0.0,0.0,1.0,0.0,2.0,101.0,165.0,106.0,179.0,-2.5,60.0,260.0,183.0,21.0,2.7,4.0,0.0,3.0,1.0,2.0,1.0,21.0,339.0,40.0,109.0,9.6,0.0,0.0,0.0,0.0,3.0,0.0,12.0,339.0,118.0,2025.0,2117.0,2121.0,Akron,13.0,64.0,Akron,Ohio,Akron Ohio,Eastern,6.0,True,41.081445,-81.519005,Seattle,Washington,Seattle Washington,Pacific,3.0,True,47.606209,-122.332071,Eastern Pacific,West,-40.813066,3.0,-3.0,3285.509950,2041.521235,2025.0,2117.0,2121.0,Akron,13.0,64.0,64.0,NaN,2025.0,2117.0,2121.0,Akron,13.0,64.0,64.0,2025.0,Akron,13.0,0.0,10.16,53.0

In [20]:
team_master.shape

(52203, 718)

In [21]:
# Check missing values

missing_data = team_master.isnull().sum()
missing_data = missing_data[missing_data > 0].sort_values(ascending=False)
print("Columns with missing data in team master Data:")
print(missing_data)

Columns with missing data in team master Data:
R32_part2                            51797
SEED_part2_x.9                       51797
S16_part2                            51797
R64_part2                            51797
FINALS_part2                         51797
YEAR_part2_x.10                      51797
BY YEAR NO_part2                     51797
BY ROUND NO_part2                    51797
E8_part2                             51797
TEAM_part2_x.10                      51797
ROUND_part2_x.9                      51797
CURRENT ROUND_part2_y                51797
YEAR_part2_y.5                       51797
TEAM_part2_y.5                       51797
F4_part2                             51797
Z RATING_part2                       51501
TOTAL KILL SHOTS RANK                51143
TOTAL KILL SHOTS CONCEDED RANK       51143
KILL SHOTS CONCEDED PER GAME RANK    51143
KILL SHOTS PER GAME RANK             51143
KILL SHOTS CONCEDED PER GAME         51143
TOTAL KILL SHOTS CONCEDED            51143
TOTAL KILL SHOTS                     51143
KILL SHOTS PER GAME                  51143
TOUGH DRAW_part2                     50371
EASY DRAW_part2                      50371
DARK HORSE_part2                     50371
UPSET ALERT_part2                    50371
YEAR_part2_x.3                       50371
CINDERELLA_part2                     50371
ROUND_part2_x.3                      50371
SEED_part2_x.3                       50371
TEAM_part2_x.3                       50371
SEED_part2_x                         49734
POWER RATING RANK_part2              49734
POWER RATING_part2                   49734
YEAR_part2_x                         49734
TEAM_part2_x                         49734
ROUND_part2_x                        49734
VAL Z-SCORE_part2                    48700
DRAW_part2                           48700
ROUND_part2_y.9                      48674
SEED_part2_y.9                       48674
TEAM_part2_y.10                      48674
YEAR_part2_y.10                      48674
Z RATING RANK_part2                  48674
SEED_part2_y.3                       48012
TEAM_part2_y.3                       48012
YEAR_part2_y.3                       48012
POWER_part2                          48012
PATH_part2                           48012
WINS_part2                           48012
POOL VALUE_part2                     48012
POOL S-RANK_part2                    48012
NCAA S-RANK_part2                    48012
POWER-PATH_part2                     48012
ROUND_part2_y.3                      48012
YEAR                                 47958
RELATIVE RATING RANK                 47958
PACE ADJUST                          47958
PACE ADJUST RANK                     47958
HOME RANK                            47958
OPPONENT ADJUST RANK                 47958
TRUE TEMPO RANK                      47958
TRUE TEMPO                           47958
D RATE RANK                          47958
O RATE RANK                          47958
OPPONENT ADJUST                      47958
RELATIVE RATING                      47958
D RATE                               47958
O RATE                               47958
ROUND                                47958
SEED                                 47958
TEAM                                 47958
KADJ EM RANK CHANGE_part2            47603
KADJ EM CHANGE_part2                 47599
PRESEASON KADJ T_part2               47595
KADJ T RANK CHANGE_part2             47595
PRESEASON KADJ T RANK_part2          47595
YEAR_part2_y.4                       47595
PRESEASON KADJ D RANK_part2          47595
PRESEASON KADJ D_part2               47595
PRESEASON KADJ O RANK_part2          47595
PRESEASON KADJ O_part2               47595
PRESEASON KADJ EM_part2              47595
PRESEASON KADJ EM RANK_part2         47595
SEED_part2_y.4                       47595
ROUND_part2_y.4                      47595
TEAM_part2_y.4                       47595
ROUND_part2_x.5                      47312
SEED_part2_x.5                       47312
SEED_part2_y                         47249
ROUND_part2_y                        47249
THREES D SHARE RANK_part2            46882
DUNKS SHARE RANK_part2               46882
DUNKS FG%D RANK_part2                46882
DUNKS D SHARE RANK_part2             46882
CLOSE TWOS FG% RANK_part2            46882
THREES FG%_part2                     46882
DUNKS FG% RANK_part2                 46882
THREES SHARE RANK_part2              46882
THREES FG% RANK_part2                46882
FARTHER TWOS D SHARE RANK_part2      46882
FARTHER TWOS FG%D RANK_part2         46882
FARTHER TWOS SHARE RANK_part2        46882
FARTHER TWOS FG% RANK_part2          46882
CLOSE TWOS D SHARE RANK_part2        46882
THREES FG%D RANK_part2               46882
THREES D SHARE_part2                 46882
FARTHER TWOS D SHARE_part2           46882
DUNKS D SHARE_part2                  46882
FARTHER TWOS FG%D_part2              46882
FARTHER TWOS SHARE_part2             46882
CLOSE TWOS SHARE RANK_part2          46882
CLOSE TWOS D SHARE_part2             46882
CLOSE TWOS FG%D_part2                46882
CLOSE TWOS SHARE_part2               46882
CLOSE TWOS FG%_part2                 46882
DUNKS FG%D_part2                     46882
THREES FG%D_part2                    46882
DUNKS SHARE_part2                    46882
DUNKS FG%_part2                      46882
CONF_part2_y                         46882
TEAM_part2_y.6                       46882
TEAM ID_part2_y.2                    46882
YEAR_part2_y.6                       46882
THREES SHARE_part2                   46882
FARTHER TWOS FG%_part2               46882
CLOSE TWOS FG%D RANK_part2           46882
SCORE_part2                          46642
GAME TIME ZONE VALUE_part2           46228
COLLEGE LONGITUDE_part2              46228
GAME TIME ZONE_part2                 46228
GAME LOCATION_part2                  46228
YEAR_part2_x.9                       46228
BY YEAR NO_part2_x                   46228
BY ROUND NO_part2_x                  46228
GAME STATE_part2                     46228
GAME CITY_part2                      46228
COLLEGE LATITUDE_part2               46228
DAYLIGHT SAVINGS TIME.1_part2        46228
DAYLIGHT SAVINGS TIME_part2          46228
COLLEGE TIME ZONE VALUE_part2        46228
COLLEGE TIME ZONE_part2              46228
COLLEGE LOCATION_part2               46228
COLLEGE STATE_part2                  46228
COLLEGE CITY_part2                   46228
TEAM_part2_x.9                       46228
GAME LATITUDE_part2                  46228
SEED_part2_x.8                       46228
TIME ZONES CROSSED_part2             46228
GAME LONGITUDE_part2                 46228
DISTANCE (KM)_part2                  46228
TIME ZONES CROSSED VALUE_part2       46228
DISTANCE (MI)_part2                  46228
LONGITUDE DIFF_part2                 46228
DIRECTION_part2                      46228
TIME ZONE COMBINATION_part2          46228
ROUND_part2_x.8                      46228
YEAR_part2_y.9                       46226
BY YEAR NO_part2_y                   46226
BY ROUND NO_part2_y                  46226
TEAM_part2_y.9                       46226
SEED_part2_y.8                       46226
ROUND_part2_y.8                      46226
CURRENT ROUND_part2_x                46226
3PT%_part2_y.1                       46212
PPPO_part2_y.1                       46212
PPPD_part2_y.1                       46212
FT%_part2_y.1                        46212
OP FT%_part2_y.1                     46212
3PT%D_part2_y.1                      46212
WIN%_part2_y.1                       46212
EFG%_part2_y.1                       46212
EFG%D_part2_y.1                      46212
FTR_part2_y.1                        46212
FTRD_part2_y.1                       46212
TOV%_part2_y.1                       46212
TOV%D_part2_y.1                      46212
OREB%_part2_y.1                      46212
DREB%_part2_y.1                      46212
OP OREB%_part2_y.1                   46212
OP DREB%_part2_y.1                   46212
RAW T_part2_y.1                      46212
2PT%_part2_y.1                       46212
2PT%D_part2_y.1                      46212
BLK%_part2_y.1                       46212
L_part2_y.1                          46212
W_part2_y.1                          46212
GAMES_part2_y.1                      46212
2PTRD_part2_y.1                      46212
TALENT_part2_y.1                     46212
EXP_part2_y.1                        46212
EFF HGT_part2_y.1                    46212
AVG HGT_part2_y.1                    46212
BADJ T_part2_y.1                     46212
3PTRD_part2_y.1                      46212
3PTR_part2_y.1                       46212
BARTHAG_part2_y.1                    46212
2PTR_part2_y.1                       46212
OP AST%_part2_y.1                    46212
AST%_part2_y.1                       46212
BLKED%_part2_y.1                     46212
BADJ O_part2_y.1                     46212
BADJ D_part2_y.1                     46212
AST% RANK_part2_y.1                  46212
3PT% RANK_part2_y.1                  46212
ELITE SOS_part2_y.1                  46212
3PT%D RANK_part2_y.1                 46212
BLKED% RANK_part2_y.1                46212
OP AST% RANK_part2_y.1               46212
2PTR RANK_part2_y.1                  46212
3PTR RANK_part2_y.1                  46212
2PTRD RANK_part2_y.1                 46212
3PTRD RANK_part2_y.1                 46212
BADJT RANK_part2_y.1                 46212
AVG HGT RANK_part2_y.1               46212
EFF HGT RANK_part2_y.1               46212
EXP RANK_part2_y.1                   46212
TALENT RANK_part2_y.1                46212
FT% RANK_part2_y.1                   46212
OP FT% RANK_part2_y.1                46212
PPPO RANK_part2_y.1                  46212
PPPD RANK_part2_y.1                  46212
ELITE SOS RANK_part2_y.1             46212
WAB_part2_y.1                        46212
BLK% RANK_part2_y.1                  46212
BADJ EM_part2_y.1                    46212
FTRD RANK_part2_y.1                  46212
TOV% RANK_part2_y.1                  46212
BADJ O RANK_part2_y.1                46212
BADJ D RANK_part2_y.1                46212
BARTHAG RANK_part2_y.1               46212
EFG% RANK_part2_y.1                  46212
2PT%D RANK_part2_y.1                 46212
EFGD% RANK_part2_y.1                 46212
FTR RANK_part2_y.1                   46212
BADJ EM RANK_part2_y.1               46212
TOV%D RANK_part2_y.1                 46212
OREB% RANK_part2_y.1                 46212
DREB% RANK_part2_y.1                 46212
OP OREB% RANK_part2_y.1              46212
OP DREB% RANK_part2_y.1              46212
RAW T RANK_part2_y.1                 46212
2PT% RANK_part2_y.1                  46212
TR RATING_part2_x.1                  46205
3PT%D_part2                          46170
2PT%_part2                           46170
2PT%D_part2                          46170
3PT%_part2                           46170
OP OREB% RANK_part2                  46170
BLK%_part2                           46170
BLKED%_part2                         46170
AST%_part2                           46170
OP DREB%_part2                       46170
OP AST%_part2                        46170
RAW T_part2                          46170
EFG%D_part2                          46170
OP OREB%_part2                       46170
DREB%_part2                          46170
OREB%_part2                          46170
TOV%D_part2                          46170
TOV%_part2                           46170
FTRD_part2                           46170
FTR_part2                            46170
3PTR_part2                           46170
EFG%_part2                           46170
WIN%_part2                           46170
L_part2                              46170
2PTR_part2                           46170
PPPO_part2                           46170
2PTRD_part2                          46170
3PTRD_part2                          46170
DREB% RANK_part2                     46170
OREB% RANK_part2                     46170
TOV%D RANK_part2                     46170
TOV% RANK_part2                      46170
FTRD RANK_part2                      46170
EFGD% RANK_part2                     46170
EFG% RANK_part2                      46170
BARTHAG RANK_part2                   46170
BADJ D RANK_part2                    46170
BADJ O RANK_part2                    46170
BADJ EM RANK_part2                   46170
WAB_part2                            46170
ELITE SOS_part2                      46170
PPPD_part2                           46170
OP FT%_part2                         46170
FT%_part2                            46170
TALENT_part2                         46170
EXP_part2                            46170
EFF HGT_part2                        46170
AVG HGT_part2                        46170
BADJ T_part2                         46170
FTR RANK_part2                       46170
ELO_part2                            46170
OP DREB% RANK_part2                  46170
V 51-100 LOSS_part2_x.1              46170
V 26-50 LOSS_part2_y.1               46170
V 26-50 WINS_part2_y.1               46170
V 1-25 LOSS_part2_y.1                46170
V 1-25 WINS_part2_y.1                46170
TR RATING_part2_y.1                  46170
TR RANK_part2_y.1                    46170
ROUND_part2_y.7                      46170
SEED_part2_y.7                       46170
TEAM_part2_y.8                       46170
YEAR_part2_y.8                       46170
LAST_part2_x.1                       46170
LO_part2_x.1                         46170
HI_part2_x.1                         46170
V 51-100 WINS_part2_x.1              46170
V 51-100 LOSS_part2_y.1              46170
V 26-50 LOSS_part2_x.1               46170
V 26-50 WINS_part2_x.1               46170
V 1-25 LOSS_part2_x.1                46170
V 1-25 WINS_part2_x.1                46170
TR RANK_part2_x.1                    46170
ROUND_part2_x.7                      46170
SEED_part2_x.7                       46170
TEAM_part2_x.8                       46170
YEAR_part2_x.8                       46170
LAST_part2_y                         46170
LO_part2_y                           46170
HI_part2_y                           46170
V 51-100 LOSS_part2_y                46170
V 51-100 WINS_part2_y.1              46170
HI_part2_y.1                         46170
V 26-50 LOSS_part2_y                 46170
LUCK HI_part2                        46170
CONSISTENCY LAST_part2               46170
CONSISTENCY LO_part2                 46170
CONSISTENCY HI_part2                 46170
CONSISTENCY V 51-100 LOSS_part2      46170
CONSISTENCY V 51-100 WINS_part2      46170
CONSISTENCY V 26-50 LOSS_part2       46170
CONSISTENCY V 26-50 WINS_part2       46170
CONSISTENCY V 1-25 LOSS_part2        46170
CONSISTENCY V 1-25 WINS_part2        46170
CONSISTENCY TR RATING_part2          46170
CONSISTENCY RANK_part2               46170
LUCK LAST_part2                      46170
LUCK LO_part2                        46170
LUCK V 51-100 LOSS_part2             46170
LO_part2_y.1                         46170
LUCK V 51-100 WINS_part2             46170
LUCK V 26-50 LOSS_part2              46170
LUCK V 26-50 WINS_part2              46170
LUCK V 1-25 LOSS_part2               46170
LUCK V 1-25 WINS_part2               46170
LUCK RATING_part2                    46170
LUCK RANK_part2                      46170
SOS LAST_part2                       46170
SOS LO_part2                         46170
SOS HI_part2                         46170
SOS RATING_part2                     46170
SOS RANK_part2                       46170
LAST_part2_y.1                       46170
V 51-100 WINS_part2_y                46170
V 26-50 WINS_part2_y                 46170
RAW T RANK_part2                     46170
EFF HGT RANK_part2                   46170
RESUME_part2                         46170
NET RPI_part2                        46170
ROUND_part2_y.5                      46170
SEED_part2_y.5                       46170
TEAM_part2_x.6                       46170
YEAR_part2_x.6                       46170
ELITE SOS RANK_part2                 46170
PPPD RANK_part2                      46170
PPPO RANK_part2                      46170
OP FT% RANK_part2                    46170
FT% RANK_part2                       46170
TALENT RANK_part2                    46170
EXP RANK_part2                       46170
AVG HGT RANK_part2                   46170
GAMES_part2                          46170
BADJT RANK_part2                     46170
3PTRD RANK_part2                     46170
2PTRD RANK_part2                     46170
3PTR RANK_part2                      46170
2PTR RANK_part2                      46170
OP AST% RANK_part2                   46170
AST% RANK_part2                      46170
BLKED% RANK_part2                    46170
BLK% RANK_part2                      46170
3PT%D RANK_part2                     46170
3PT% RANK_part2                      46170
2PT%D RANK_part2                     46170
2PT% RANK_part2                      46170
WAB RANK_part2                       46170
B POWER_part2                        46170
V 1-25 LOSS_part2_y                  46170
V 26-50 WINS_part2_x                 46170
V 1-25 WINS_part2_y                  46170
TR RATING_part2_y                    46170
TR RANK_part2_y                      46170
ROUND_part2_y.6                      46170
SEED_part2_y.6                       46170
TEAM_part2_y.7                       46170
YEAR_part2_y.7                       46170
LAST_part2_x                         46170
LO_part2_x                           46170
HI_part2_x                           46170
V 51-100 LOSS_part2_x                46170
V 51-100 WINS_part2_x                46170
V 26-50 LOSS_part2_x                 46170
V 1-25 LOSS_part2_x                  46170
Q1 W_part2                           46170
V 1-25 WINS_part2_x                  46170
TR RATING_part2_x                    46170
TR RANK_part2_x                      46170
ROUND_part2_x.6                      46170
SEED_part2_x.6                       46170
TEAM_part2_x.7                       46170
YEAR_part2_x.7                       46170
BID TYPE_part2                       46170
R SCORE_part2                        46170
PLUS 500_part2                       46170
Q3 Q4 L_part2                        46170
Q1 PLUS Q2 W_part2                   46170
Q2 W_part2                           46170
W_part2                              46170
OREB%_part2_x                        46170
BARTHAG_part2                        46170
ELITE SOS_part2_y                    46170
BLKED%_part2_y                       46170
AST%_part2_y                         46170
OP AST%_part2_y                      46170
2PTR_part2_y                         46170
3PTR_part2_y                         46170
2PTRD_part2_y                        46170
3PTRD_part2_y                        46170
BADJ T_part2_y                       46170
AVG HGT_part2_y                      46170
EFF HGT_part2_y                      46170
EXP_part2_y                          46170
TALENT_part2_y                       46170
FT%_part2_y                          46170
OP FT%_part2_y                       46170
PPPO_part2_y                         46170
BLK%_part2_y                         46170
3PT%D_part2_y                        46170
3PT%_part2_y                         46170
TOV%_part2_y                         46170
L_part2_y                            46170
WIN%_part2_y                         46170
EFG%_part2_y                         46170
EFG%D_part2_y                        46170
FTR_part2_y                          46170
FTRD_part2_y                         46170
TOV%D_part2_y                        46170
2PT%D_part2_y                        46170
OREB%_part2_y                        46170
DREB%_part2_y                        46170
OP OREB%_part2_y                     46170
OP DREB%_part2_y                     46170
RAW T_part2_y                        46170
2PT%_part2_y                         46170
PPPD_part2_y                         46170
WAB_part2_y                          46170
GAMES_part2_y                        46170
BADJ EM RANK_part2_y                 46170
BLK% RANK_part2_y                    46170

# Save final dataframe for analysis

In [22]:
# Export dataframe
# Path
path = r'/Users/tyrasmussen/Desktop/FVTC/Spring 2026/Data Analytics Capstone/MM/MM Data/FINAL'

In [24]:
# Save final dataframe to pickle
full_kenpom_df.to_pickle(os.path.join(path, 'MM_Data_Initial_Clean.pkl'))