# Import

In [100]:
# Load all modules needed for EDA
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#from scipy import stats
#from sklearn.preprocessing import LabelEncoder
#from sklearn.model_selection import train_test_split
#from sklearn.linear_model import LogisticRegression
#from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


# Set display options
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 1000)

In [86]:
# Create path

path = r'/Users/tyrasmussen/Desktop/FVTC/Spring 2026/Data Analytics Capstone/MM/MM Data/FINAL'

In [87]:
# Import cleaned/validated pickle file
df = pd.read_pickle(os.path.join(path, 'FINAL_Valid_MMData.pkl'))

# Inspect data structure

In [88]:
df.head()

   season          team_name  efgpct_off  topct_off  orpct_off  ftrate_off  efgpct_def  topct_def  orpct_def  ftrate_def conference  adjusted_temo  raw_tempo  adjusted_offensive_efficiency  raw_offensive_efficiency  adjusted_defensive_efficiency  raw_defensive_efficiency  avg_possession_length_(offense)  avg_possession_length_(defense)  avgheight  centerheight  pfheight  sfheight  sgheight  pgheight  effectiveheight  experience  bench  centerpts  pfpts  sfpts  sgpts  pgpts  centeror   pfor   sfor   sgor   pgor  centerdr   pfdr   sfdr   sgdr   pgdr     fg2pct     fg3pct      ftpct   blockpct  oppfg2pct  oppfg3pct   oppftpct  oppblockpct    fg3rate  oppfg3rate      arate   opparate   stlrate  oppstlrate       dfp    nstrate  oppnstrate      offft   off2ptfg   off3ptfg      defft   def2ptfg   def3ptfg  seed    tempo  adjtempo        oe     adjoe       de     adjde     adjem post-season_tournament tournament_winner tournament_championship? final_four? top_12_in_ap_top_25_during_week_6?
0    2025  Abilene Christian   46.689148  20.740433  30.069238   37.155120   51.411290  24.010102  31.450720   51.276882        WAC           69.6       70.1                           97.7                      95.7                          102.3                     100.8                             16.8                             17.5      77.31         -0.37     -0.84     -0.23      0.68      1.31            -0.60    1.341230  34.05      23.57  23.58  23.82  12.66  16.37     30.57  29.91  22.05   7.76   9.71     19.37  26.10  22.05  16.78  15.70  47.826087  28.883495  71.947195   8.366534  52.589641  32.644628  69.200524    11.156686  25.260576   32.526882  51.566952  51.603499  0.142011    0.111754  5.314202   9.565000    9.809005  22.256253  59.520163  18.223583  25.655977  51.311953  23.032070   9.0  70.0679   69.6271   95.6706   97.6737  100.773  102.3350  -4.66102                    NaN                No                       No          No                                 No
2    2025          Air Force   50.092822  20.721288  22.736031   35.396040   54.635950  15.684864  29.064039   35.437998        MWC           64.6       64.7                           98.9                      95.3                          111.7                     113.1                             19.8                             17.0      78.18          1.08     -0.23      0.01      1.13      2.88             0.43    1.789850  28.89      26.40  22.02  18.77  19.57  13.19     34.11  18.56  15.99  14.11  17.19     17.93  15.96  21.71  25.38  18.97  50.540216  33.077905  63.461538   8.028546  54.772525  36.263736  69.983949    12.364946  48.452970   36.234357  62.941176  48.639053  0.086818    0.104566  5.314202  10.264712    7.003028  18.314834  42.482341  39.202825  18.498091  52.100127  29.401782   9.0  64.6651   64.6373   95.3082   98.9098  113.105  111.6740 -12.76410                    NaN                No                       No          No                                 No
3    2025              Akron   54.940898  16.354727  32.179054   26.950355   50.073783  17.270259  29.474548   33.054599        MAC           71.7       72.5                          113.6                     114.9                          107.1                     105.1                             15.8                             17.1      75.06         -1.94     -3.52     -2.16     -1.36     -1.75            -2.73    1.399620  38.91      19.00  17.71  21.16  17.74  24.35     48.76  18.17  14.88  11.53   6.57     33.22  19.19  20.43  15.44  11.65  55.220017  36.401674  75.087719   9.754163  50.991277  32.383420  72.321429     7.506471  45.200946   37.973438  57.894737  45.128779  0.102789    0.097795  5.314202   6.575183    6.991334  15.552326  46.511628  37.936047  19.270420  50.991277  29.738303  13.0  72.5396   71.6561  114.8680  113.5550  105.141  107.0810   6.47358          March Madness                No                       No          No                                 No
4    2025            Alabama   56.600590  16.559930  33.725202   39.308309   47.820055  13.488046  29.426752   33.174792        SEC           75.3       76.1                          126.8                     118.4                           96.5                     106.2                             14.9                             16.7      78.07          1.61      3.10      0.21     -0.47     -0.12             2.35    2.986970  38.57      15.78  19.15  18.97  20.78  25.32     29.10  29.93  26.62   9.42   4.92     26.91  29.47  20.19  12.26  11.16  59.747435  35.326087  71.995708  10.121212  49.030303  30.355097  70.967742    12.075770  46.562632   34.601665  55.448997  44.692737  0.080505    0.101690  5.314202   6.390933    5.437589  20.000000  45.126677  34.873323  19.753908  53.807782  26.438311   2.0  76.0703   75.2702  118.4340  126.8140  106.226   96.4694  30.34500          March Madness                No                       No          No                                Yes
5    2025        Alabama A&M   45.098039  21.938360  33.911535   38.581315   54.301403  20.994775  34.647303   46.674802       SWAC           71.2       71.8                           92.2                      94.8                          115.6                     110.0                             16.2                             17.1      76.76          0.63     -0.25     -0.62     -0.37     -1.61             0.19    0.864071  43.82      17.42  18.47  17.69  25.99  20.37     34.51  17.80  24.06  14.95   8.63     22.45  24.04  16.66  20.44  16.35  44.323791  30.790569  66.666667  10.742188  51.757812  39.024390  70.196078     8.687068  41.580161   37.522880  53.353204  57.792208  0.109456    0.124081  5.314202   9.530212   10.049184  22.189055  44.676617  33.134328  23.176521  45.748813  31.074666   9.0  71.8121   71.2333   94.8255   92.2313  109.965  115.5890 -23.35810                    NaN                No                       No          No                                 No

In [89]:
df.shape

(10111, 79)

In [90]:
# Print column names and data types for sql
print(df.dtypes)

season                                  int64
team_name                              object
efgpct_off                            float64
topct_off                             float64
orpct_off                             float64
ftrate_off                            float64
efgpct_def                            float64
topct_def                             float64
orpct_def                             float64
ftrate_def                            float64
conference                             object
adjusted_temo                         float64
raw_tempo                             float64
adjusted_offensive_efficiency         float64
raw_offensive_efficiency              float64
adjusted_defensive_efficiency         float64
raw_defensive_efficiency              float64
avg_possession_length_(offense)       float64
avg_possession_length_(defense)       float64
avgheight                             float64
centerheight                          float64
pfheight                              float64
sfheight                              float64
sgheight                              float64
pgheight                              float64
effectiveheight                       float64
experience                            float64
bench                                 float64
centerpts                             float64
pfpts                                 float64
sfpts                                 float64
sgpts                                 float64
pgpts                                 float64
centeror                              float64
pfor                                  float64
sfor                                  float64
sgor                                  float64
pgor                                  float64
centerdr                              float64
pfdr                                  float64
sfdr                                  float64
sgdr                                  float64
pgdr                                  float64
fg2pct                                float64
fg3pct                                float64
ftpct                                 float64
blockpct                              float64
oppfg2pct                             float64
oppfg3pct                             float64
oppftpct                              float64
oppblockpct                           float64
fg3rate                               float64
oppfg3rate                            float64
arate                                 float64
opparate                              float64
stlrate                               float64
oppstlrate                            float64
dfp                                   float64
nstrate                               float64
oppnstrate                            float64
offft                                 float64
off2ptfg                              float64
off3ptfg                              float64
defft                                 float64
def2ptfg                              float64
def3ptfg                              float64
seed                                  float64
tempo                                 float64
adjtempo                              float64
oe                                    float64
adjoe                                 float64
de                                    float64
adjde                                 float64
adjem                                 float64
post-season_tournament                 object
tournament_winner                      object
tournament_championship?               object
final_four?                            object
top_12_in_ap_top_25_during_week_6?     object
dtype: object

In [91]:
df.head()

   season          team_name  efgpct_off  topct_off  orpct_off  ftrate_off  efgpct_def  topct_def  orpct_def  ftrate_def conference  adjusted_temo  raw_tempo  adjusted_offensive_efficiency  raw_offensive_efficiency  adjusted_defensive_efficiency  raw_defensive_efficiency  avg_possession_length_(offense)  avg_possession_length_(defense)  avgheight  centerheight  pfheight  sfheight  sgheight  pgheight  effectiveheight  experience  bench  centerpts  pfpts  sfpts  sgpts  pgpts  centeror   pfor   sfor   sgor   pgor  centerdr   pfdr   sfdr   sgdr   pgdr     fg2pct     fg3pct      ftpct   blockpct  oppfg2pct  oppfg3pct   oppftpct  oppblockpct    fg3rate  oppfg3rate      arate   opparate   stlrate  oppstlrate       dfp    nstrate  oppnstrate      offft   off2ptfg   off3ptfg      defft   def2ptfg   def3ptfg  seed    tempo  adjtempo        oe     adjoe       de     adjde     adjem post-season_tournament tournament_winner tournament_championship? final_four? top_12_in_ap_top_25_during_week_6?
0    2025  Abilene Christian   46.689148  20.740433  30.069238   37.155120   51.411290  24.010102  31.450720   51.276882        WAC           69.6       70.1                           97.7                      95.7                          102.3                     100.8                             16.8                             17.5      77.31         -0.37     -0.84     -0.23      0.68      1.31            -0.60    1.341230  34.05      23.57  23.58  23.82  12.66  16.37     30.57  29.91  22.05   7.76   9.71     19.37  26.10  22.05  16.78  15.70  47.826087  28.883495  71.947195   8.366534  52.589641  32.644628  69.200524    11.156686  25.260576   32.526882  51.566952  51.603499  0.142011    0.111754  5.314202   9.565000    9.809005  22.256253  59.520163  18.223583  25.655977  51.311953  23.032070   9.0  70.0679   69.6271   95.6706   97.6737  100.773  102.3350  -4.66102                    NaN                No                       No          No                                 No
2    2025          Air Force   50.092822  20.721288  22.736031   35.396040   54.635950  15.684864  29.064039   35.437998        MWC           64.6       64.7                           98.9                      95.3                          111.7                     113.1                             19.8                             17.0      78.18          1.08     -0.23      0.01      1.13      2.88             0.43    1.789850  28.89      26.40  22.02  18.77  19.57  13.19     34.11  18.56  15.99  14.11  17.19     17.93  15.96  21.71  25.38  18.97  50.540216  33.077905  63.461538   8.028546  54.772525  36.263736  69.983949    12.364946  48.452970   36.234357  62.941176  48.639053  0.086818    0.104566  5.314202  10.264712    7.003028  18.314834  42.482341  39.202825  18.498091  52.100127  29.401782   9.0  64.6651   64.6373   95.3082   98.9098  113.105  111.6740 -12.76410                    NaN                No                       No          No                                 No
3    2025              Akron   54.940898  16.354727  32.179054   26.950355   50.073783  17.270259  29.474548   33.054599        MAC           71.7       72.5                          113.6                     114.9                          107.1                     105.1                             15.8                             17.1      75.06         -1.94     -3.52     -2.16     -1.36     -1.75            -2.73    1.399620  38.91      19.00  17.71  21.16  17.74  24.35     48.76  18.17  14.88  11.53   6.57     33.22  19.19  20.43  15.44  11.65  55.220017  36.401674  75.087719   9.754163  50.991277  32.383420  72.321429     7.506471  45.200946   37.973438  57.894737  45.128779  0.102789    0.097795  5.314202   6.575183    6.991334  15.552326  46.511628  37.936047  19.270420  50.991277  29.738303  13.0  72.5396   71.6561  114.8680  113.5550  105.141  107.0810   6.47358          March Madness                No                       No          No                                 No
4    2025            Alabama   56.600590  16.559930  33.725202   39.308309   47.820055  13.488046  29.426752   33.174792        SEC           75.3       76.1                          126.8                     118.4                           96.5                     106.2                             14.9                             16.7      78.07          1.61      3.10      0.21     -0.47     -0.12             2.35    2.986970  38.57      15.78  19.15  18.97  20.78  25.32     29.10  29.93  26.62   9.42   4.92     26.91  29.47  20.19  12.26  11.16  59.747435  35.326087  71.995708  10.121212  49.030303  30.355097  70.967742    12.075770  46.562632   34.601665  55.448997  44.692737  0.080505    0.101690  5.314202   6.390933    5.437589  20.000000  45.126677  34.873323  19.753908  53.807782  26.438311   2.0  76.0703   75.2702  118.4340  126.8140  106.226   96.4694  30.34500          March Madness                No                       No          No                                Yes
5    2025        Alabama A&M   45.098039  21.938360  33.911535   38.581315   54.301403  20.994775  34.647303   46.674802       SWAC           71.2       71.8                           92.2                      94.8                          115.6                     110.0                             16.2                             17.1      76.76          0.63     -0.25     -0.62     -0.37     -1.61             0.19    0.864071  43.82      17.42  18.47  17.69  25.99  20.37     34.51  17.80  24.06  14.95   8.63     22.45  24.04  16.66  20.44  16.35  44.323791  30.790569  66.666667  10.742188  51.757812  39.024390  70.196078     8.687068  41.580161   37.522880  53.353204  57.792208  0.109456    0.124081  5.314202   9.530212   10.049184  22.189055  44.676617  33.134328  23.176521  45.748813  31.074666   9.0  71.8121   71.2333   94.8255   92.2313  109.965  115.5890 -23.35810                    NaN                No                       No          No                                 No

In [103]:
# Find numerical values outside of expected ranges of 0 - 100, besides the 'season' column which is expected to have values greater than 100
#numerical_cols = df.select_dtypes(include=[np.number]).columns  
#for col in numerical_cols:
 #   out_of_range = df[(df[col] < 0) | (df[col] > 100)]
  #  if not out_of_range.empty:
   #     print(f"Column '{col}' has values outside the range of 0 to 100:")
    #    print(out_of_range[[col]])

In [92]:
# Download pickle file to csv for SQL
df.to_csv(os.path.join(path, 'FINAL_Valid_MMData.csv'), index=False)

# Create new format for SQL transfer

In [93]:
# conferences

#conferences_df = (
   # df[['conference']]
  #  .drop_duplicates()
 #   .reset_index(drop=True)
#)

#conferences_df['conference_id'] = conferences_df.index + 1

In [94]:
# Teams
#teams_df = df[['team_name','conference']].drop_duplicates()

#teams_df = teams_df.merge(
 #   conferences_df,
  #  on='conference',
   # how='left'
#)

#teams_df = teams_df[['team_name','conference_id']]

#teams_df['team_id'] = teams_df.index + 1

In [95]:
# Season
#seasons_df = df[['season']].drop_duplicates().reset_index(drop=True)

#seasons_df['season_id'] = seasons_df.index + 1

In [96]:
# Connect to relational keys
#df = df.merge(teams_df[['team_id','team_name']], on='team_name')

#df = df.merge(seasons_df[['season_id','season']], on='season')

In [97]:
# Tournament Results
#tournament_df = df[[
   # 'team_id',
    #'season_id',
    #'seed',
    #'post-season_tournament',
    #'tournament_winner',
    #'tournament_championship?',
    #'final_four?',
    #'top_12_in_ap_top_25_during_week_6?'
#]].copy()

In [98]:
#from sqlalchemy import create_engine

#server = 'ETL10'
#database = 'March_Madness'

#connection_string = f"mssql+pyodbc://@{server}/{database}?driver=ODBC+Driver+17+for+SQL+Server"

#engine = create_engine(connection_string)

In [99]:
#df.to_sql("staging_team_data", engine, if_exists="replace", index=False)